### ISSUE TITLE
Could there be a design flaw in the way files are stored ?

### ISSUE THREAD

**Issue by salhdev** [Qoraiche/laravel-mail-editor#10]
Hi again,
The templates are stored in : 
vendor/qoraiche/laravel-mail-editor/resources/views/templates/
where vendor/* is ignored in git => So the result of that is that all your dev and changes in the templates will not be taken in the testing nor production environment !
And also template data is stored in a data table which is also not taken in the git.
Why not create a Templates directory within the app/Mail directory and store it there ?

**Comment by Qoraiche** [comment]
Hi @salhdev,
Thanks for reporting this I will take this into consideration in the next updates,

Thanks again.

**Comment by griffins** [comment]
Exactly what i was wondering

**Comment by griffins** [comment]
Just found out about this package today from laravel news. I love it.
My only problem is the need to modify my database schema. I would love if the package could maintain its meta data in a json file instead of the db. Am willing to make a pr for the same

**Comment by griffins** [comment]
Am doing a PR for this issue, what do you think about the views existed in the default namespace instead of the maileclipse one?

**Comment by griffins** [comment]
Hi i did a PR for the first task.

**Comment by keatwei** [comment]
after i do composer update, my existing template is not accessible

**Comment by griffins** [comment]
Its because of where the files are being stored. sorry about that. @keatwei Once we get my PR merged that would be fixed

**Comment by griffins** [comment]
Also if you drop your database you will loose them

**Comment by keatwei** [comment]
@griffins ya.. if possible can put in resources/view/emails would be great
thx for your effort and package

**Comment by griffins** [comment]
I already did that. Actually you can customize the folder you want

**Comment by griffins** [comment]
For the second task there is PR https://github.com/Qoraiche/laravel-mail-editor/pull/13 which should fix  known issues preventing the package from being used in production

**Comment by Qoraiche** [comment]
@griffins thanks for your PRs I will take a look at it tomorrow when I come back home

Thanks again.

**Comment by dbfx** [comment]
Any word on a plan to make this easy to migrate into production?

**Comment by Qoraiche** [comment]
Hello @dbfx, @salhdev 

Please update to the latest version (currently 1.1.7), now you can override templates views using the following publishing command:

`php artisan vendor:publish --tag=maileclipse.templates`

Also, there is no need for database migration, all templates metadata will be stored in a JSON file.

hope this helps,
Thanks

**Comment by dbfx** [comment]
Great thank you! Sent a contribution to the project from Snapt!

**Comment by Qoraiche** [comment]
@dbfx thank you so much
