### ISSUE TITLE
Add support for language files

### ISSUE THREAD

**Issue by dgillier** [Qoraiche/laravel-mail-editor#101]
Hello,

I tried to add @lang params while editing a template but this is really making the preview unusable.

<img width="1129" alt="Screenshot 2020-06-09 at 16 03 50" src="https://user-images.githubusercontent.com/37960204/84157289-dc72fc80-aa6a-11ea-9436-2b8d87dc47b8.png">

not sure how to solve this, any idea ?
Thanks, Denis

**Comment by ReeceM** [comment]
Hi @dgillier, do they not render when you are previewing the mailable?

I was going to suggest using the `{{ __("email.teacher_validation.learn_more") }}` to also render language files, but it would still look the same in the template editor.

The language files should render though when you are looking at the mailable that the template has been attached to, I think the blade `@lang` aren't going to be rendered in the template editor as it's not passed through the View compiler of Laravel.

Could you confirm if the issues is that it isn't rendering or if it is in the template side of things you would like a better display of the language file?
