### ISSUE TITLE
Pretember for Hacktoberfest - Please Read First

### ISSUE THREAD

**Issue by ReeceM** [Qoraiche/laravel-mail-editor#104]
# Contributors

It is awesome that you would like to help with the MaileEclipse package, there will be issues tagged as `Hacktoberfest`.  Please read this brief list of things about contributing on the repo

Please have a read of this, https://github.com/Qoraiche/laravel-mail-editor/blob/master/contributing.md

- If you would like to work on the issues that are available, please claim them with a comment and also ask for any assistance if you are unsure about something.
- If you are unable to complete the PR, or would like someone else to handle it, please mention it so in the comments.
- Please keep community standards in the messages and commits.
- *One* feature per PR to keep it in scope, if you have different things, you can open a new PR for that different feature

--- 
Original Message below

Hi @Qoraiche,

As Hacktoberfest is around the corner again this year, and with September it is set as a time for preparing the repos for getting ready for it.

I was wondering if we can start going through some of the issues on the repo and seeing which ones can be marked for those who would like to get involved in Hacktoberfest and like to support the packages development.

We could have a poll even of some issues that could be tagged and refined to what can be sorted.

This would be nice as there are some simple issues and some other things that contributors could add, and possibly some of the previous contributors.

There is the discord channel if there are newcomers to contributing and would like some help from the community [https://discord.gg/hacktoberfest](https://discord.gg/hacktoberfest)

I think we could have some comments tagged into this issue with links to the issues that some think could be tagged as hacktoberfest

**Comment by ReeceM** [comment]
###  Feature: search/filter in Mailables #80 

This could be possible by using the same method in the son search tool used in jigsaw.

**Comment by ReeceM** [comment]
### Feature to send test emails to users. #98

**Comment by ReeceM** [comment]
### Website / documentation offline #99

This one may just be more practical to get people back into using the package or maybe make a static version hosted on something like vercel or netlify

**Comment by ReeceM** [comment]
Also @Qoraiche I hope you are keeping well and have been in good health as I haven't seen you active on the repo 👍

**Comment by ReeceM** [comment]
How to insert Picture ? #100

**Comment by Qoraiche** [comment]
> Hi @Qoraiche,
> 
> As Hacktoberfest is around the corner again this year, and with September it is set as a time for preparing the repos for getting ready for it.
> 
> I was wondering if we can start going through some of the issues on the repo and seeing which ones can be marked for those who would like to get involved in Hacktoberfest and like to support the packages development.
> 
> We could have a poll even of some issues that could be tagged and refined to what can be sorted.
> 
> This would be nice as there are some simple issues and some other things that contributors could add, and possibly some of the previous contributors.
> 
> There is the discord channel if there are newcomers to contributing and would like some help from the community https://discord.gg/hacktoberfest
> 
> I think we could have some comments tagged into this issue with links to the issues that some think could be tagged as hacktoberfest

Hello @ReeceM, sounds great, let's go for it! I did join the discord channel you provide 🚀

**Comment by Qoraiche** [comment]
> Also @Qoraiche I hope you are keeping well and have been in good health as I haven't seen you active on the repo 👍

Hey, yeah, unfortunately, I'm extremely busy those days :(, but let's go for this

**Comment by ReeceM** [comment]
Hi @Qoraiche, awesome I am glad you are still well. 

Awesome that we can encourage some more contribution 😄

**Comment by ReeceM** [comment]
Hi @Qoraiche, 

Not sure if you have seen this tweet https://twitter.com/hacktoberfest/status/1312221208667185153?s=20

If not, not sure if you want to label the repo ? At least if anyone has made PRs for the event they won't feel like they have done it for no reason. 

And it is a decent thing for DO to have done for the event.

**Comment by Qoraiche** [comment]
> Hi @Qoraiche,
> 
> Not sure if you have seen this tweet https://twitter.com/hacktoberfest/status/1312221208667185153?s=20
> 
> If not, not sure if you want to label the repo ? At least if anyone has made PRs for the event they won't feel like they have done it for no reason.
> 
> And it is a decent thing for DO to have done for the event.

Hi @ReeceM, Thanks for pointing me out to this, I certainly didn't see that tweet 👍 

I've added the **hacktoberfest** label to the repo.

Thank you!
