### ISSUE TITLE
Laravel 8 support ?

### ISSUE THREAD

**Issue by lilouch** [Qoraiche/laravel-mail-editor#106]
Laravel 8 has been released. The current version of laravel mail editor is not compatible with this version. Is there a way to add support for laravel 8 ?

Thank

**Comment by ReeceM** [comment]
Hi @lilouch thank you for opening the feature request. 

Support for Laravel 8 will be looked at. Thank you :+1:

**Comment by ReeceM** [comment]
Hi, 

Could you run `composer require qoraiche/laravel-mail-editor:dev-laravel-8-support` on your laravel 8 app to confirm that you are getting the expected results too 👍

**Comment by lilouch** [comment]
Seems to work ! Thank a lot for the quick fix ! =D

**Comment by ReeceM** [comment]
@lilouch Awesome 👍 

It will be tagged then with the latest version

**Comment by ReeceM** [comment]
Hi @lilouch,

We are looking at supporting Laravel 8 via `v3` of MailEclipse

So just a heads-up so that you are aware of that. 

As well as anyone else looking for Laravel 8 support. 

**See [#108](https://github.com/Qoraiche/laravel-mail-editor/pull/108)**

**Comment by ReeceM** [comment]
Hi @lilouch v3 is tagged, please feel free to open a bug report if there are any issues 👍
