### ISSUE TITLE
PSR Classname compliance

### ISSUE THREAD

**Issue by ReeceM** [Qoraiche/laravel-mail-editor#110]
It would be good to get all the classnames and namespaces to make use of PSR standards so that the compose autoload system and classmaps all function correctly and as expected.

There are a few classes and files that have lowercase first parts of the names.

This is a good issue for new comers helping on the repo 👍

**Comment by yogendra-revanna** [comment]
Hi @ReeceM,

I would like to work on this.

**Comment by ReeceM** [comment]
Hi @yogendra-revanna, 

Thank you.

I just want to check with you, are you wanting the contributions to count toward the Hacktoberfest event?

**Comment by yogendra-revanna** [comment]
No @ReeceM. Nothing like that, I was using this package and thought I could contribute.

**Comment by ReeceM** [comment]
@yogendra-revanna, Okay that is awesome, thank you. Really appreciated 💯 

I was just concerned if they are merged they wouldn't count. But this one would be useful to have done before October, so please continue with it :)

**Comment by yogendra-revanna** [comment]
@ReeceM, Please check the commit. I will send the pull request if you give a go-head.

**Comment by ReeceM** [comment]
Hi @yogendra-revanna, thank you very much 😄.


With the composer file, I don't think is necessary to have duplicates of the alias in the psr-4 autoload and the one for the alias.

The below two could be adjusted:

This is accurate for the psr-4 autoload entry: `"Qoraiche\\MailEclipse\\": "src/"`

https://github.com/yogendra-revanna/laravel-mail-editor/blob/1a834be54597580a0a9736865c8647e993182008/composer.json#L42-L43

`"MailEclipse": "Qoraiche\\MailEclipse\\Facades\\MailEclipse",` for the alias

https://github.com/yogendra-revanna/laravel-mail-editor/blob/1a834be54597580a0a9736865c8647e993182008/composer.json#L27-L28

**Comment by yogendra-revanna** [comment]
I had left them as a fallback, so that If anyone referencing outside this repo with the old namespace should not face anyissue.

**Comment by ReeceM** [comment]
@yogendra-revanna I don't think that will be an issue. If we keep the other formats, we may be encouraging end users to keep the lower case structure.

In all I don't think there is a common use case for the package that someone would be referencing something for the repo. If they do have issues, the error should be clear.

But I don't mind helping if someone opens an issue because of that in the future. 

It would just be better and clearer for the future if there is one reference to the 'src/' directory and then one for the alias that Laravel loads up.

**Comment by yogendra-revanna** [comment]
Sure @ReeceM, will update and send the pull request 👍
