### ISSUE TITLE
When creating mailable, user input is used for a class name, but it's not properly sanitised

### ISSUE THREAD

**Issue by ivebe** [Qoraiche/laravel-mail-editor#116]
**Is your feature request related to a problem? Please describe.**
If user enter `123` as an mailable name, file will be created in `App\Mail\123.php` and class name will be `class 111 extends Mailable`, which is not valid class name. Same goes for `null`, `interface`, or any other reserved keywords.
https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class
https://www.php.net/manual/en/reserved.keywords.php

**Describe the solution you'd like**
1) Validate class name as per https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class
2) Since blacklisting keywords will never be 100% bulletproof, adding some prefix/suffix to the class names would solve the problem. I propose adding 'Mail' prefix so even if someone create mailable that starts with a number it would still work. 

If prefix is not appropriate, and suffix looks better, we would have to do additional check that first character is either a letter or underscore, and return message to the user with error.

**Additional context**
I've already made a solution that sanitise input and add prefix to class: https://github.com/ivebe/laravel-mail-editor/commit/1fefb661d753d1a660c3e0fad2ae7100f85a04b4 

If other approach is desired, I'm open to contribute.

**Comment by ReeceM** [comment]
Hi there,

I like this feature addition as a whole as it would account for random name creation and errors if someone is writing test classes and putting random things in.

I agree with the fact that a blacklist of keywords would be pointless as that would have to be updated for any releases of PHP itself. 


### Suggestions

- [ ] 1. Add the `Mail` as a suffix rather. This would be more inline with what Laravel users are used to and exposed to in tutorials
- [ ] 2. Check if the user has added the `Mail` word at the end of the class. This would prevent `SomethingMailMail` sort of weirdness.
- [ ] 2.1 The validation should also account if the user just puts `Mail` as the class, in that case, should append `Mail` so there aren't conflicts.
- [ ] 3 For the error response, maybe now or at some point we can add a bit more explanation as to the correct format or 'what not to have in a name' for the mailable.


Other than those few things, the feature seems valid.

I am not sure if @Qoraiche would like to add anything further and also if this should be targeted at v3.x of the package?

**Comment by ivebe** [comment]
Sure, just in case of suffix, we need to verify that User input starts with either a letter, or underscore, as those are requirements for class name. I believe Str::slug will remove all unwanted characters, so from the frontend point of view user should be only notified that name of mailable must start with a letter (or underscore) and that it can't be empty. Other cases should be covered by Str:slug and adding Mail suffix.

If @Qoraiche doesn't anything else to add, I would start with this and submit a PR.

**Comment by Qoraiche** [comment]
> Sure, just in case of suffix, we need to verify that User input starts with either a letter, or underscore, as those are requirements for class name. I believe Str::slug will remove all unwanted characters, so from the frontend point of view user should be only notified that name of mailable must start with a letter (or underscore) and that it can't be empty. Other cases should be covered by Str:slug and adding Mail suffix.
> 
> If @Qoraiche doesn't have anything else to add, I would start with this and submit a PR.

Thanks for pointing this enhancement @ivebe,

Sure, it would be great to open a PR for it, also @ReeceM's mentioned suggestions (https://github.com/Qoraiche/laravel-mail-editor/issues/116#issuecomment-702736734) are really worthful to follow
