### ISSUE TITLE
Raw HTML

### ISSUE THREAD

**Issue by eNzyOfficial** [Qoraiche/laravel-mail-editor#12]
Apologies if I've overlooked this feature, but it would be nice to be able to see the raw HTML rather than just the WYSIWYG version, I'd like to use this as a way for marketing to make minor changes to templates without having to go through version control and this looks like it would work great, but it seems like it's tied to using the templates. Is this something you would consider adding? I imagine it would be a case of adding the button to the tinyMCE toolbar?

Thanks!

**Comment by Qoraiche** [comment]
Hi @eNzyOfficial I've added a **view source code** button to the WYSIWYG editor, please update to the new version (currectly **v1.1.5**) - commit https://github.com/Qoraiche/laravel-mail-editor/commit/ea5af6cb9b9866841ce73b6d09d541d287a1328f
