### ISSUE TITLE
[Discussion] Refactoring Class files

### ISSUE THREAD

**Issue by ReeceM** [Qoraiche/laravel-mail-editor#129]
I have been working on and wanting to suggest the refactoring of the files of the MailEclipse package for a while as it may improve maintainability and also encourage future contribution from users who may see the opportunity to improve or fix something in the package.

Is this something that would be accepted and good to be done for the package?

If need be, the branch is on: `feature/break-up-classes` - https://github.com/ReeceM/laravel-mail-editor/tree/feature/break-up-classes

It has some ideas of moving stuff around and also moving the regex for cleaning and switching out blade components to the config file. I was thinking that one benefit of this is that it would allow users to add their own custom components and that the filter can also account for those.

Some other changes are refactoring the facade and also making the main class non-static functions, that is the only breaking thing 'technically' but the facade can then be used for that as all the methods currently there will remain.

You can see some of the other changes there, I am not sure if the latest updates were pushed at present.

**Comment by Qoraiche** [comment]
> I have been working on and wanting to suggest the refactoring of the files of the MailEclipse package for a while as it may improve maintainability and also encourage future contributions from users who may see the opportunity to improve or fix something in the package.

Hey @ReeceM, yeah that's awesome, this is really what I was thinking to enhance but unfortunately didn't have much time yet ⌛ , so as you said this will encourage future contribution to the package which is awesome.

> 
> Is this something that would be accepted and good to be done for the package?

yes, of course, sounds good we can start with this as a refactoring launch 👍🏼 , can you open a new PR for it

**Comment by ReeceM** [comment]
Hey @Qoraiche, that will be awesome then. I will get the latest changes made across as some of it was done before the new changes and I'll get a PR open 👍
