### ISSUE TITLE
Method CreateMailable on the controller doesn't work and leads to non-existent view

### ISSUE THREAD

**Issue by ReeceM** [Qoraiche/laravel-mail-editor#132]
It appears that if the endpoint for the createMailable method is hit, the view doesn't exist. 

this happens if the js hasn't loaded, the modal doesn't open up.

this method should be removed to prevent issues, as the file doesn't exist and the flow for creating the mailable exists. :)

https://github.com/Qoraiche/laravel-mail-editor/blob/a78120156b1fdff057b1d2c89834f85c51a045d1/src/Http/Controllers/MailablesController.php#L34-L37

/linked #129

**Comment by Qoraiche** [comment]
thanks for reporting, would be great if you can push the changes
