### ISSUE TITLE
Can't use class members to pass down to my Markdown from within the Mailable.

### ISSUE THREAD

**Issue by phadaphunk** [Qoraiche/laravel-mail-editor#137]
**Describe the bug**
Can't add a class member to my Mailable.

```
class PasswordResetMail extends Mailable
{
    use Queueable, SerializesModels;
    public $url;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($url)
    {
        $this->url = $url;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->markdown('password.reset')->with('url', $this->$url);
    }
}
```

In this example, `public $url` throws when accessing `myapp.dev/maileclipse/mailables`

**Trace**:
`Return value of Qoraiche\MailEclipse\MailEclipse::viewDataInspect() must be of the type array or null, none returned `

`..\vendor\qoraiche\laravel-mail-editor\src\MailEclipse.php:827`

Can't use `protected` or `private` because it throws as well but because of member visibility.

**Laravel Application**: `8`

**Maileclipse package version**: `3.2`

**Comment by ReeceM** [comment]
Thank you for this, will have a look in a bit, as well as the other issue raised 👍🙂

**Comment by phadaphunk** [comment]
@ReeceM the `viewDataInspect` function should return `null` if the other instanceof do not pass. It fixes the issue as well. Should I PR this?

**Comment by ReeceM** [comment]
@phadaphunk if you can put that together it would be great, thank you :) , I will have a look at it in an hour or so though. 

If you do need it, you should be able to tag it locally in your composer file, you can check under versions in packagist to see what the version ID is for it
