### ISSUE TITLE
Giving the weird error Return value of Qoraiche\MailEclipse\MailEclipse::viewDataInspect() must be of the type array or null, none returned

### ISSUE THREAD

**Issue by P-d0309** [Qoraiche/laravel-mail-editor#139]
**Describe the bug**
I have installed the package in fresh Laravel and it returns this error
**Return value of Qoraiche\MailEclipse\MailEclipse::viewDataInspect() must be of the type array or null, none returned**
when I hit the URL of **http://127.0.0.1:8000/maileclipse/mailables**

**Laravel Application**: version
8.16.2
**Maileclipse package version**: version
3.2.2
**Screenshots**
![6e177d07-6629-4146-be85-8cd419d54aaa](https://user-images.githubusercontent.com/37208444/100726691-47363c80-33eb-11eb-943c-5a00bead4e68.png)

**Comment by Qoraiche** [comment]
Hey, thanks for reporting, @ReeceM I think this should be fixed after the fix https://github.com/Qoraiche/laravel-mail-editor/pull/138?

**Comment by ReeceM** [comment]
Hi @P-d0309, sorry that you have had this bug and thank you for reporting it.

I thought it was in the v3.2.2 release. But it is now with v3.2.3

**Comment by ReeceM** [comment]
@Qoraiche I was just typing a reply to this :), it is fixed with the PR #138, I just tagged the release with that fix.

**Comment by ReeceM** [comment]
Hey @P-d0309, when you have a chance and update. Would you be able to ping me if it’s working alright. 👍

**Comment by ReeceM** [comment]
I am closing this issue as it should be resolved now. 

If there is still an issue, please re-open this one.
