### ISSUE TITLE
[Suggestion] not limited to mail also add custom notification

### ISSUE THREAD

**Issue by lukylook** [Qoraiche/laravel-mail-editor#14]
hay
nice project!

but why limited only for emails ?
you could add custom notification (like text-plan as sms)
thank you

**Comment by Qoraiche** [comment]
Hi @lukylook,

Can you please explain this feature more?

**Comment by realrashid** [comment]
Hey @lukylook ,

If i'm not wrong i think you are talking about this https://youtu.be/QFgEGNBY3FI?t=235.

**Comment by henryavila** [comment]
I think that @lukylook wanna say is: to use this awsome package to create notification templates.
So, instead to create a new mailable for every notification, can use a single template to sande different notification.

https://laravel.com/docs/5.7/notifications#formatting-mail-messages

**Comment by Qoraiche** [comment]
@henryavila yes you right.

**Comment by Qoraiche** [comment]
duplicated, planned on v5
