### ISSUE TITLE
[3.x] Editable Mail files for Notification classes

### ISSUE THREAD

**Issue by lstables** [Qoraiche/laravel-mail-editor#146]
More of a question that good be a feature I guess.

For how great this package is, is it/would it be possible to have mail notifications editable as well as Mailables? Or is it just a case of Mailables?

**Comment by ReeceM** [comment]
Hi Lee, so I think it was asked before, I think #14 is related to this question.

I don't think there has been much activity on it recently and also on that issue specifically either.

I would just like to check, as the Notifications can have views, as well as the method calls to build a notification, which part are you thinking of being editable via the package?

Also on the notifications, you can have different `via` channels/options. So not sure if you are thinking of having those editable too?

**Comment by lstables** [comment]
So when you a notification is made and you specify email really have those editable

**Comment by ReeceM** [comment]
> So when you a notification is made and you specify email really have those editable

Cool, so basically the view file that is referenced by the notification. That is a easier starting point to integrate that feature

**Comment by lstables** [comment]
Yeah you got it.

**Comment by Qoraiche** [comment]
https://github.com/Qoraiche/laravel-mail-editor/issues/14 - Duplicated. planned on v5
