### ISSUE TITLE
Trying to get property 'token' of non-object

### ISSUE THREAD

**Issue by gurinder-xyrintech** [Qoraiche/laravel-mail-editor#15]
i got error Trying to get property 'token' of non-object"
when i pass object though construct is there an alternative solution to solve this

`protected $token, $user_name;

 public function __construct($user_activation)
    {
        $this->token = $user_activation->token;
        $this->user_name = $user_activation->user->name;
    }`

**Comment by IvalinV** [comment]
Can you provide more information about how and when you got this issue ?

**Comment by gurinder-xyrintech** [comment]
> Can you provide more information about how and when you got this issue ?

when i run locahost/maileclipse 
if i remove those lines it runs smoothly

**Comment by Qoraiche** [comment]
Hi, @gurinder-xyrintech thanks for reporting this,

Please be patient I will fix this problem in the next updates.

Thanks again,

**Comment by lstables** [comment]
Any ETA on this fix?

**Comment by mauriziocalarese** [comment]
Waiting for the update, this issue blocks me too.

ps. anyway thanks for the package ;)

**Comment by lstables** [comment]
@Qoraiche any update then this issue is likely to be fixed please :)

**Comment by akiyamaSM** [comment]
How can I reproduce the error?

**Comment by elephantux** [comment]
I still got same error. Which version of package install to resolve it?

**Comment by Qoraiche** [comment]
Hello Everyone,

Please update to the latest version (currently **v1.1.10**), Checkout PR https://github.com/Qoraiche/laravel-mail-editor/pull/28.
