### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by lstables** [Qoraiche/laravel-mail-editor#16]
Every mailable I have as different properties and params added to it, but I keep getting the above error:

````
public $property;
public $tenant;

  /**
     * @param $certs
     */
    public function __construct($property, $tenant)
    {
        $this->property = $property;
        $this->tenant   = $tenant;
    }
 
    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        $message = $this->markdown('emails.tenant.pack')->subject('Tenant Pack for ' . $this->property->address . ' is now ready');
        return $message;
    }
````

**Comment by lstables** [comment]
Is there a way to overcome/fix this, so that the mailables can be edited?

**Comment by Qoraiche** [comment]
Hi @lstables thanks for reporting this,

This issue is already mentioned in the #15 issue, i will fix this problem very soon.

Thanks again

**Comment by lstables** [comment]
Great and ETA on that fix?

**Comment by lstables** [comment]
Hey @Qoraiche Do you have plans to get this fixed, if so what sort of time frame are we looking at? :)

**Comment by Qoraiche** [comment]
Hello Everyone,

Please update to the latest version (currently **v1.1.10**), Checkout PR https://github.com/Qoraiche/laravel-mail-editor/pull/28.
