### ISSUE TITLE
Not support Laravel 8 with PHP 8

### ISSUE THREAD

**Issue by dominservice** [Qoraiche/laravel-mail-editor#165]
## Describe the bug

  Problem 1
    - This package requires php ^7.3 but your PHP version (8.0.7) does not satisfy that requirement.
  Problem 2
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your PHP version (8.0.7) does not satisfy that requirement.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your PHP version (8.0.7) does not satisfy that requirement.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your PHP version (8.0.7) does not satisfy that requirement.
    - Installation request for fzaninotto/faker (locked at v1.9.2, required as ^1.9.1) -> satisfiable by fzaninotto/faker[v1.9.2].

## Reproduction steps
on install

## Laravel Version: 
Laravel 8 with PHP 8

## MailEclipse package version: 
not installed

---

**Comment by ReeceM** [comment]
Hi there @dominservice

Thank you for highlighting this, we will have to make sure that those dependencies are suited to PHP 8.x

**Comment by ReeceM** [comment]
Hey @dominservice the package recently updated, please confirm if it is installing now. It is installing on Laravel 9, if you are using that version now.

**Comment by ReeceM** [comment]
Hi I am going to close this as the package is installing on Laravel 8 and PHP 8 instances
