### ISSUE TITLE
Environment Not Allowed

### ISSUE THREAD

**Issue by adriano461997** [Qoraiche/laravel-mail-editor#166]
## Describe the bug
I've followed all the steps but I keep giving this error.

## Laravel Version: 
Laravel 8.53.1

## MailEclipse package version: 
name     : qoraiche/laravel-mail-editor
descrip. : Laravel Mailable Editor
keywords : laravel, laravel-mail, laravel-mailable, mailEclipse, mailable, mailable-editor, markdown
versions : * v3.4.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://github.com/Qoraiche/laravel-mail-editor
source   : [git] https://github.com/Qoraiche/laravel-mail-editor.git 5c39835e3f7a76a11e8ac16a4d77d552ab265c0f
dist     : [zip] https://api.github.com/repos/Qoraiche/laravel-mail-editor/zipball/5c39835e3f7a76a11e8ac16a4d77d552ab265c0f 5c39835e3f7a76a11e8ac16a4d77d552ab265c0f
path     : C:\laragon\wapangola\vendor\qoraiche\laravel-mail-editor
names    : qoraiche/laravel-mail-editor

support
issues : https://github.com/Qoraiche/laravel-mail-editor/issues
source : https://github.com/Qoraiche/laravel-mail-editor/tree/v3.4.1

autoload
psr-4
Qoraiche\MailEclipse\ => src/

requires
illuminate/support ^8.0
laravel/legacy-factories ^1.0
reecem/mocker ^1.1

requires (dev)
mockery/mockery ~1.2
orchestra/testbench ^6.0
phpunit/phpunit ^8.0|^9.0
sempro/phpunit-pretty-print ^1.0

**Comment by ReeceM** [comment]
Hi there Adriano, 

the reason for this error is the configuration for the Laravel `APP_ENV` value  (the Laravel environment)

Would you be able to share what you have it set to?

The package will work in 

```php
'allowed_environments' => ['local', 'development', 'staging', 'testing'],
```

If this error happens, it would most likely be that the App isn't in one of those environments? Maybe not listed in english in the config file?

**Comment by adriano461997** [comment]
Thank you very much, solved my error.

**Comment by ReeceM** [comment]
Hey @adriano461997 I'm glad it's sorted 👍 😄
