### ISSUE TITLE
Unknown Column name field

### ISSUE THREAD

**Issue by Akhibemudu** [Qoraiche/laravel-mail-editor#17]
@Qoraiche  Thanks for this wonderful package, Is there a way to use a different table instead of the default users table, currently am not sure one can use the package without having users table, I tried it and I got unknown field name in users table. Thank you.

**Comment by Qoraiche** [comment]
I'm not sure what are you dealing with exactly, but the package will not restrict you to do anything with your application tables.
Can you share your mailable, please?

**Comment by Akhibemudu** [comment]
@Qoraiche at first, when I installed the package, I couldn't access the maileclipse dashboard because of unknown field "name" in users table, however, I fixed this by creating a new field "name" in the users table.
So my question is "if the package can be used without having users table" . Secondly, am finding it difficult to use foreach loop with the package, and lastly, is it save editing the view from maileclipse::templates.sendPropertyAlertEmail ?

**Comment by ChiselspeedTuning** [comment]
Is this related to the `Illegal string offset 'name'` issue?

**Comment by Qoraiche** [comment]
@Akhibemudu please install the latest version and try again,

let me know if your problem fixed or not.
