### ISSUE TITLE
Adding segmentation and workflow mailers

### ISSUE THREAD

**Issue by cadentic** [Qoraiche/laravel-mail-editor#175]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is.

## Describe the solution you'd like
Adding segmentation and workflow mailers 

## Additional context
we can easily add segmentation and workflow mailer automation within any email sending app. can we have such a thing here with payment or donation links and social share?

can we have the same behind jetstream inertial for laravel 8

**Comment by ReeceM** [comment]
Hi @cadentic,

Thank you for your feature suggestion. Would it be possible for you to provide an example of what you are referring to? Or an example of the other emailing app?

Just want to know that everyone is on the same page :)

**Comment by cadentic** [comment]
mautic openemm

**Comment by ReeceM** [comment]
Hi @cadentic 

I had to search that as it was relatively vague. But looking further it seems that the OpenEMM is a marketing system and the codebase of MailEclipse from what I can tell isn't targeted at that?

Maybe @Qoraiche would be able to have a look and also share what route can be taken on this, the one that would be better suited to the request.

**Comment by cadentic** [comment]
open EMM is an email marketing system and it is java and oracle based but workflow mailers and segmentation help to maintain compliance properly while we will be doing a mass mailing. mautic is PHP based integrated with gatsbyjs , mjml with lots of plugins it works similarly to open EMM.

**Comment by Qoraiche** [comment]
sounds like a good idea @cadentic, but at the moment we are not planning to turn the package into a marketing tool, as a matter of fact, we may add the support to develop mailable views based on the MJML framework and also preview it.
