### ISSUE TITLE
ErrorException Undefined array key "string" 

### ISSUE THREAD

**Issue by sainani8897** [Qoraiche/laravel-mail-editor#178]
getting this error 
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/qoraiche/laravel-mail-editor/src/MailEclipse.php:647

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/83855777/134661729-57261e36-7876-4979-bdea-3605c86fbc26.png)

**Comment by ReeceM** [comment]
Hi @sainani8897 

thank you for raising the issue. Will have a look in a little bit. 

In the meantime, would it be possible to let me know in the meantime if you have string type hint in the model constructor?
