### ISSUE TITLE
Mail Stubs are ignored

### ISSUE THREAD

**Issue by anishsarkar** [Qoraiche/laravel-mail-editor#185]
## Describe the bug
Mail Editor web interface generation of mailables seems to ignore and updates to the mail.stub 

## Reproduction steps
1.  Publish the stubs by : 
> php artisan stub:publish

2. Go to the stubs directory. Edit the mail.stub. I added 

- on top
> use \App\Models\User;

- in the class 

> public User $user;
> public function __construct(User $user) 
> {
>    $this->user = $user;
> }

Save the stub. 

2. Click on ** Add Mailables ** on ** Mailables ** menu.
4. Generate a new markdown Mailable following the instruction. Check the mailable created. It does not have the updated versions of the stub file. 

5. Use the command line 
> php artisan make:mail NewMailable

The commandline generated Mailable has the updated code. 

## MailEclipse package version: v3.5.0

--- 

<details>
Default configuration. No changes done. Testing out the laravel-mail-editor package. 
</details>

**Comment by ReeceM** [comment]
Hi there @anishsarkar,

thank you for highlighting this. The stubs are a new feature in Laravel v8. But the mailables are made using the command line interface from artisan. So not sure why that is happening. 

Will have a look why then it isn't working

**Comment by anishsarkar** [comment]
My bad! I also needed to update "markdown-mail.stub" so that both types of mail html as well as markdown mails are updated.

**Comment by ReeceM** [comment]
Hey @anishsarkar 

No worries, glad that you have it sorted then 💯
