### ISSUE TITLE
Add support for language files

### ISSUE THREAD

**Issue by anubhav217** [Qoraiche/laravel-mail-editor#186]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is.

**Comment by ReeceM** [comment]
Hi @anubhav217 

There isn't any information on this issue. Would you be able to please expand on this. 

I may close it in favor of other issues and PRs that exist on this already :)

**Comment by ReeceM** [comment]
I will be closing this issue as there seems to be a set of 'serial' issues opened across different repo's using the same pattern of very little information and no responses.
