### ISSUE TITLE
Uncaught SyntaxError: "" string literal contains an unescaped line break

### ISSUE THREAD

**Issue by hmreumann** [Qoraiche/laravel-mail-editor#187]
## Describe the bug
I have a mailable that uses the User Model, and some other Models.
When I try to edit the mailable I have this error in the console:
"Uncaught SyntaxError: "" string literal contains an unescaped line break"
After I remove the user model from the mailable the error disappears.

## Laravel Version: 
8.73.1

## MailEclipse package version: 
v3.5.0

## Screenshots (if applicable)

![imagen](https://user-images.githubusercontent.com/36493144/144488682-db750682-344d-4dc4-96df-13dbd98f4656.png)

**Comment by ReeceM** [comment]
Thanks @hmreumann.

Would it be possible to provide the Mailable class code and the view code? 

The below repo doesn't have that code in the screenshot. https://github.com/hmreumann/laravel-mail-issue-recreation

**Comment by hmreumann** [comment]
I'm sorry but that recreation is old @ReeceM

**Comment by ReeceM** [comment]
> I'm sorry but that recreation is old @ReeceM . As I try to recreate it in a brand new laravel project it doesn't fail. We have a lot of relations in our User Model and a big users table. Maybe something is happening with that. Every mailable that has the User Model is throwing that error.

Okay. I thought that might have been an older one 💯 :)

With the new one it sounds like there might be something being returned that shouldn't be inside the view. I think there might be strings being injected at run time.

**Comment by ReeceM** [comment]
Would it be possible to share the view file and the mailable class? I would like to see if I can test that locally on my test app for the package. @hmreumann 👍

**Comment by hmreumann** [comment]
@ReeceM Can we somehow make a call and I can show you. I'm working on a private repository.

**Comment by ReeceM** [comment]
@hmreumann I could share my discord or my twitter if you would prefer to dm it that way, it is late evening here so not sure your timezone.

But I am happy to do that then if you want to set a time.

**Comment by hmreumann** [comment]
@ReeceM I've just sent you a twitter message.

**Comment by ReeceM** [comment]
Hey @hmreumann, found the issue, but will need to have a look at why specifically it may be happening.

**Comment by hmreumann** [comment]
Great @ReeceM I'm available as you need. You are awesome.

**Comment by ReeceM** [comment]
Could you try and remove the address field from the factory? So maybe just set it to `$this->faker->streetAddress(),` where you were using `$this->faker->address(),`

This isn't a user side bug, but it will help me to see if it is reproducible because of this type of text format.

**Comment by hmreumann** [comment]
I'm not using $this->faker->address() , actually I'm using $this->faker->unique()->streetAddress().

**Comment by hmreumann** [comment]
That was a bit difficult to find. Thankyou very much @ReeceM

**Comment by ReeceM** [comment]
> I found the related factory that had the address() and yes, I changed it to streetAddress() and that was it.

Awesome, that confirms what I thought might be the reason. Will make a pre-release that you can try and then let me know if it's working 👍 

I will be making a fix that will let you put it back to `address()`. 

The reason for the issue was that `address()` has a newline character in it and the frontend the side with javascript isn't interpreting it properly.
