### ISSUE TITLE
Environment Not Allowed

### ISSUE THREAD

**Issue by anubhav217** [Qoraiche/laravel-mail-editor#189]
## Screenshots (if applicable)

--- 

<details>
<summary> <b>Additional information</b></summary>

</details>

**Comment by ReeceM** [comment]
Please refer to #184 and https://github.com/Qoraiche/laravel-mail-editor/issues/166#issuecomment-894320153

Please note I am closing this as you are repeating this pattern of 'serial' issues on multiple repositories without information. Please add information on your next issue or I _will_ request that you are restricted from this repository. 

It would be interesting to find out if this is registered as a bot. As the previous issue used the same title as other closed issues.
