### ISSUE TITLE
Please make the editor screen as Fullscreen (container-fluid) 

### ISSUE THREAD

**Issue by toRichie** [Qoraiche/laravel-mail-editor#192]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is.

**Comment by ReeceM** [comment]
Hi @toRichie,

Thank you for opening the request. I notice that there is only the title of the issue filled in and not the other sections. It would make it easier if you could provide a good motivation for this request, or if you would like to make a contribution to the project that would also be welcomed once it's cleared up to which editor.
