### ISSUE TITLE
syntax error, unexpected token ")"

### ISSUE THREAD

**Issue by AliKHODR** [Qoraiche/laravel-mail-editor#199]
## Describe the bug
I get `syntax error, unexpected token ")"` when i go to http://localhost/maileclipse/mailables. but everything else seems to work just fine.

## Reproduction steps
1. Go to : http://localhost/maileclipse/mailables
2. See error : syntax error, unexpected token ")"

## Laravel Version: 
Laravel 9

## MailEclipse package version: 
v 4.0.2

**Comment by ReeceM** [comment]
Hi there @AliKHODR

Are you able to provide more information on the line numbers and such of the error?

**Comment by ReeceM** [comment]
Its also possible with ignition installed by default to generate a public share of the error, it will auto delete after a few days. This may be better too @AliKHODR 😄

**Comment by AliKHODR** [comment]
https://flareapp.io/share/oPR4RkJ5#share

**Comment by ReeceM** [comment]
> is this enough https://flareapp.io/share/oPR4RkJ5#share?

It is thank you 💯 , PR #200 should fix it

**Comment by AliKHODR** [comment]
Fantastic !! thank you guys !!
