### ISSUE TITLE
Database storage for templates

### ISSUE THREAD

**Issue by emil-nasso** [Qoraiche/laravel-mail-editor#20]
Like the looks of this package so far! Great potential. :)

An idea that I just wanted to dump here.

It would be really cool if you could store the templates in the database and if this package never modified any files.

Using docker, source control (git) or most kinds of deploy kind of makes it a big no-no to change php-files (anything outside of the storage folder really).

Would that be possible?

**Comment by dstollie** [comment]
This issue is related to the discussion I started in this PR: https://github.com/Qoraiche/laravel-mail-editor/pull/13

**Comment by Qoraiche** [comment]
@dstollie yes it's but possible but I'm still collecting feedbacks to decide what I need to do in the next updates.

**Comment by Qoraiche** [comment]
Hello @emil-nasso

https://github.com/Qoraiche/laravel-mail-editor/issues/10#issuecomment-482238082

> Please update to the latest version (currently 1.1.7), now you can override templates views using the following publish command:
> 
> `php artisan vendor:publish --tag=maileclipse.templates`
> 
> Also, there is no need for database migration, all templates metadata will be stored in a JSON file.
> 
> hope this helps,
> Thanks
