### ISSUE TITLE
v3 Error installing on Laravel 8

### ISSUE THREAD

**Issue by nosfas** [Qoraiche/laravel-mail-editor#205]
## Describe the bug
When trying to install on Laravel, composer fails.

When running the composer command the following message is shown.

> Illuminate\Contracts\Container\BindingResolutionException
>  Target class [Qoraiche\MailEclipse\Command\VendorPublishCommand] does not exist.´

## Reproduction steps
1. Run composer require qoraiche/laravel-mail-editor:3

## Laravel Version: 
Laravel Framework 8.83.7

## MailEclipse package version: 
versions : * v3.0.0

**Comment by ReeceM** [comment]
Hi @nosfas,

Thank you for highlighting this issue. 

This seems to be the second time this has happened. 

Would you be able to tell me the PHP version you are running at the moment?

**Comment by ReeceM** [comment]
Hi, please can you install 

`composer require qoraiche/laravel-mail-editor:^3.4` it has the fix already for a namespace error. At present it is only grabbing a fixed version of version 3, not one of the latest v3 tags.

That will remove the install error

**Comment by nosfas** [comment]
That fixed it.
Thank you.
