### ISSUE TITLE
Attempt to read property "email" on null

### ISSUE THREAD

**Issue by vigneshvickkyk** [Qoraiche/laravel-mail-editor#213]
ErrorException
Attempt to read property "email" on null
http://localhost/job/maileclipse/mailables

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\xampp\htdocs\job\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php:612

![image](https://user-images.githubusercontent.com/69624763/177039060-2a1c2297-1c01-4233-8d4d-1d696975a4b5.png)
please help!

**Comment by ReeceM** [comment]
Hi there @vigneshvickkyk 

It is possible that you don't have a default user set in the config file for the preview email. 


Another place to check is the .env file of the Paracelsus app for the default from address

**Comment by vigneshvickkyk** [comment]
@ReeceM  Thanks for your swift response. I have checked these files after your answered. 

The real problem is my own mail functions in the App\Mail. So i have deleted all my mail functions and again write the mail functions , Its works very well now.

Again Thanks for your response.
