### ISSUE TITLE
axios.post is not a function

### ISSUE THREAD

**Issue by RJonwal** [Qoraiche/laravel-mail-editor#215]
## Describe the bug

Hii, 
I installed the maileclipse package with laravel 9. I'm not able to create any new mailable class or template. whenever I try to create a mailable class or template and submit the form**, the same error occurred "axios.post is not a function"** 
can you please help me with this issue?

only mailables  listing & templates listing is working, 
not able to add any new template or mailable class.

## Laravel Version: 
Laravel 9

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/53889941/194524139-db1d3dbc-3d60-42ef-a43c-fced9b8b00a4.png)

![image](https://user-images.githubusercontent.com/53889941/194525367-7ad57af3-e1cb-4d85-bcbf-22e309eb8ecb.png)

**Comment by ReeceM** [comment]
Hi @RJonwal 

Thank you for opening the issue

I'll have a look at it today and come back

**Comment by ReeceM** [comment]
Hi @RJonwal 

Would you be able to let me know the setup of that laravel app? Was it just a default install or with one of the starters?
