### ISSUE TITLE
Markdown Button save &gt;

### ISSUE THREAD

**Issue by mtmSchoenberger** [Qoraiche/laravel-mail-editor#216]
## Describe the bug
The markdown save wrong

## Reproduction steps
1. Edit an mailable
2. add Button and click update
3. Click on Preview

## Laravel Version: 
Laravel Framework 8.83.19

## MailEclipse package version: 
versions : * v3.5.3

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/55283261/198307324-768fe407-fda4-4862-a3be-03c88bbd09a7.png)

**Comment by ReeceM** [comment]
Hi there, does this only happen when you use the button or on most of the markdown components that have the `>` character?

**Comment by mtmSchoenberger** [comment]
If i cllick on update this payload is send to the server:
![image](https://user-images.githubusercontent.com/55283261/199048134-d4ac5353-3f4c-488f-bf76-bd96eb166f04.png)

**Comment by ReeceM** [comment]
Thank you @mtmSchoenberger I'll have a look why this is happening again as we did resolve a similar issue with the conversion of some characters to those HTML characters

**Comment by ReeceM** [comment]
So I am trying to reproduce this and it's not giving me the same issue, are you able to maybe create a simplified repository that has the same issues you are having and link it here?

**Comment by ReeceM** [comment]
Hi there @mtmSchoenberger 

Have you been able to create a repo that is having the same issues?

It will help greatly as currently it doesn't look like this is an widespread bug?

**Comment by mtmSchoenberger** [comment]
Hey @ReeceM 

Sorry I haven't gotten around to doing a test with a clean Laravel installation yet.
I will have a closer look tomorrow.
I will give you feedback about my test on monday.  

### Version 4 is only for Laravel 9 or does this also go in Laravel 8? I have not tested this yet.

**Comment by ReeceM** [comment]
Sorry my mistake on version 4 being available on both 🤦‍♂️

As and when you can do a test that would be great, thank you 👍

**Comment by mtmSchoenberger** [comment]
Hey @ReeceM,

I have now tested with a clean installation of Laravel Framework 8.83.26 and MailEclipse package versions v3.5.3 and it works. 

Except for the "promotion" element:
`Error: View [promotion] not found. (View: \laravel-mail-editor\resources\views\draft\MtmTestMail.blade.php).`

So it seems to be a problem with compatibility to another package :(
Then I have to search where the problem occurs. Maybe it helps to update the packages.

**Comment by mtmSchoenberger** [comment]
@ReeceM 
Are there any known packages that could cause problems with MailEclipse?

**Comment by Qoraiche** [comment]
thanks for your feedback @mtmSchoenberger, it seems like a conflict with another package, we're not really aware of any other packages that may have compatibility issues with maileclipse, but as a workaround, you can register a new component for the promotion and start using it in the mailable view template.

**Comment by ReeceM** [comment]
> @ReeceM 
> 
> Are there any known packages that could cause problems with MailEclipse?

The only package that I know had issues was the Scout Melliesearch package. That was a db isssue. 


I had the issue you having the other day with just a normal app without the package. If you can confirm the view exists sometimes it's a view cache issue. composer dumpautoload sorts it sometimes. 

But let me know if that sorts it. If not I'll spin up a copy of laravel 8 to test tonight

**Comment by mtmSchoenberger** [comment]
> > @ReeceM
> > Are there any known packages that could cause problems with MailEclipse?
> 
> The only package that I know had issues was the Scout Melliesearch package. That was a db isssue.
> 
> I had the issue you having the other day with just a normal app without the package. If you can confirm the view exists sometimes it's a view cache issue. composer dumpautoload sorts it sometimes.
> 
> But let me know if that sorts it. If not I'll spin up a copy of laravel 8 to test tonight

The error with the "promotion" component is due to the fact that as of Laravel 7 the "promotion" component has been removed. [Source](https://sam-ngu.medium.com/laravel-mail-markdown-components-list-293fbca048f).
In "\vendor\laravel\framework\src\Illuminate\Mail\resources\views\html" are also only button, panel and table no promotion component.

This means that you must either remove the button in the editor or add the component manual.
composer dumpautoload does not fix this.

**Comment by ReeceM** [comment]
Oh yes! I forgot that as I never noticed as I had exported the html for the mailables and notifications in my own app.

I wasn't able to get around to looking into this in an example app last night, but I am looking at it now so will get you some feedback in a bit

**Comment by ReeceM** [comment]
Hi @mtmSchoenberger I have setup an example app with laravel 8 and have test, I am not getting this error? 

Not sure if it is a system settings issue or so. But I am linking the repo here, please could you clone and run it locally to see if you get the same issues

https://github.com/ReeceM/test-issue-216-pacakge

You'll just need to setup a default database. Even sqlite is okay for now with this test.

**Comment by mtmSchoenberger** [comment]
Hey @ReeceM,
which PHP version do you use?
I use PHP v8.1.

I have installed your repo locally and was able to create templates even with buttons. Only the "promotion" problem is still there.

That means something in my main installation collides with the email editor. :(

I'll keep researching the problem and give feedback when I find a solution.

**Comment by ReeceM** [comment]
Hi @mtmSchoenberger 

I'm currently running PHP8.0 on my computer. 

For the promotion component, if you create it in the directory structure Laravel exports the mail components it should find that from the frameworks side. 

Are you able then to create a repo of a Laravel app. Then add the dependencies you use one by one till it dies?

Then could you push that? Even if it's a fork of the repo I linked.

**Comment by mtmSchoenberger** [comment]
I have now fixed the problem temporarily by customizing the MailablesController and the MailablesPreviewController.

That works for now.

I have investigated this and found that "Request" changes. 
If I use ` $request->markdown` I get the markdown with the error but if I use ` $request->getContent()` I get the json string without error. So there must be some package filtering the JSON request. 

```php
 public function parseTemplate(Request $request)
    {

        $template = $request->has('template') ? $request->template : false;

        $viewPath = $request->has('template') ? $request->viewpath : base64_decode($request->viewpath);

        // ref https://regexr.com/4dflu
        $bladeRenderable = preg_replace('/((?!{{.*?-)(&gt;)(?=.*?}}))/', '>', $request->markdown);
        //Customization here
        $bladeRenderable = str_replace("&gt;", ">", $bladeRenderable);

        if (MailEclipse::markdownedTemplateToView(true, $bladeRenderable, $viewPath, $template)) {
            return response()->json([
                'status' => 'ok',
            ]);
        }

        return response()->json([
            'status' => 'error',
        ]);
    }
```
```php
 public function markdownView(Request $request)
    {
        // ref https://regexr.com/4dflu
        $bladeRenderable = preg_replace('/((?!{{.*?-)(&gt;)(?=.*?}}))/', '>', $request->markdown);
        $bladeRenderable = str_replace("&gt;", ">", $bladeRenderable);
        return MailEclipse::previewMarkdownViewContent(false, $bladeRenderable, $request->name, false, $request->namespace);
    }
```

**Comment by ReeceM** [comment]
That is interesting and odd at the same time. Would you be able to share a list of the devDependencies and dependencies you have in the composer.json of your app where MailEclipse is installed?

---

Another note, does changing the call to `$request->input('markdown')` produce the same bug? Also if this is a consistent fix and you have time please feel free to make a PR.

**Comment by mtmSchoenberger** [comment]
Hey @ReeceM,

I have found the Problem.
I used this package: stevebauman/purify
There was a middleware which cleaned the request:

```PHP
namespace App\Http\Middleware;

use Stevebauman\Purify\Facades\Purify;
use Illuminate\Foundation\Http\Middleware\TransformsRequest;

class XssSanitizer extends TransformsRequest
{
    /**
     * Transform the given value.
     *
     * @param  string  $key
     * @param  mixed  $value
     * @return mixed
     */
    protected function transform($key, $value)
    {
        return Purify::clean($value);
    }
}
```

I remove the middleware  from Kernel.php and the e-mail editor works perfect.

So it was my fault not a fault in the package.
This issues can be closed.

**Comment by ReeceM** [comment]
Hi @mtmSchoenberger thanks for the feedback and also finding what was causing issues for you. 

I do think we can keep the issue open, as what you did to fix it can possibly done across the package to make sure we use the input / getContent methods if the package doesn't interfere with those
