### ISSUE TITLE
Method App\Mail\RepoTestMail::build() does not exist

### ISSUE THREAD

**Issue by Ah-ahmed2022** [Qoraiche/laravel-mail-editor#218]
Method App\Mail\RepoTestMail::build() does not exist when trying to create new mail on laravel 9

**Comment by ReeceM** [comment]
Hi is this in the latest version of Laravel 9?

Would you be able to give the exact version of Laravel 9 or create a simple repo to reproduce this issue as it will make it quicker to resolve. I do think that the new version of the mail system changed, but I don't think they deprecated the method.

**Comment by Ah-ahmed2022** [comment]
Hello, laravel 9.37.0

On the maileclipse/mailables page Add mailable this will generate RepoTestMai.php without  public function build() because it is replaced by public function content() so I thing something need to be updated 
Thank

**Comment by Ah-ahmed2022** [comment]
namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class RepoTestMail extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the message envelope.
     *
     * @return \Illuminate\Mail\Mailables\Envelope
     */
    public function envelope()
    {
        return new Envelope(
            subject: 'Repo Test Mail',
        );
    }

    /**
     * Get the message content definition.
     *
     * @return \Illuminate\Mail\Mailables\Content
     */
    public function content()
    {
        return new Content(
            markdown: 'markdown_test2.view',
        );
    }

    /**
     * Get the attachments for the message.
     *
     * @return array
     */
    public function attachments()
    {
        return [];
    }
    
  
}

**Comment by ReeceM** [comment]
> Hello, laravel 9.37.0 On the maileclipse/mailables page Add mailable this will generate RepoTestMai.php without public function build() because it is replaced by public function content() so I thing something need to be updated Thank

Yes so that is what I am suspecting about the changes have / will be causing this issue.

Thank you for creating an issue about it, will have to have a look at how this can be corrected

**Comment by Qoraiche** [comment]
> > Hello, laravel 9.37.0 On the maileclipse/mailables page Add mailable this will generate RepoTestMai.php without public function build() because it is replaced by public function content() so I thing something need to be updated Thank
> 
> Yes so that is what I am suspecting about the changes have / will be causing this issue.
> 
> Thank you for creating an issue about it, will have to have a look at how this can be corrected

Hello @ReeceM, thanks for working on the fix,

It seems like many changes have been done to the mailable structure since laravel [v9.37.0](https://github.com/laravel/framework/blob/9.x/CHANGELOG.md#v9370---2022-10-25), a new property and method (Content) on the mailable content class added to supply a raw HTML string, also to provide the view with data; (checkout the PR for more info https://github.com/laravel/framework/pull/44703), I think since this update it will be much easier to extract data as used to be with the build() method, as it is directly accessible using the **Content** class

````php
public function content() {
    return new Content(
        raw: 'raw html string',
        with: [
          'name' => 'Reecem'
        ],
    );
}
```` 

````php
$mail = new \App\Mail\ContactAdmin();

dd($mail->content()->with);
````

**Comment by ReeceM** [comment]
Hey @Qoraiche,

Sorry I've been slow on updating some things though.

But I was looking into making some adjustments that would allow it to work on both v8 and v9 of Mailable classes as I think you can still use the old way?

```php
    public static function buildMailable($instance, $type = 'call')
    {
🔶 // create a check here or later on in this method to change the method being called, either build / render...
        if ($type === 'call') {
            if (self::handleMailableViewDataArgs($instance) !== null) {
                return app()->call([self::handleMailableViewDataArgs($instance), 'build']);
            }

            return app()->call([new $instance, 'build']);
        }

        return app()->make($instance);
    }
```

Specifically this part of the MailEclipse class, we could make it call the render method or the build method. Depending on what it is or the Laravel version.

---

But the PR linked gives more info on what I saw and does appear to allow for a cleaner approach that could be implemented. I will have a look this weekend how to implement using the content class.

**Comment by ReeceM** [comment]
Hey @Qoraiche,

Sorry I've been slow on updating some things though.

But I was looking into making some adjustments that would allow it to work on both v8 and v9 of Mailable classes as I think you can still use the old way?

```php
    public static function buildMailable($instance, $type = 'call')
    {
🔶 // create a check here or later on in this method to change the method being called, either build / render...
        if ($type === 'call') {
            if (self::handleMailableViewDataArgs($instance) !== null) {
                return app()->call([self::handleMailableViewDataArgs($instance), 'build']);
            }

            return app()->call([new $instance, 'build']);
        }

        return app()->make($instance);
    }
```

Specifically this part of the MailEclipse class, we could make it call the render method or the build method. Depending on what it is or the Laravel version.

---

But the PR linked gives more info on what I saw and does appear to allow for a cleaner approach that could be implemented. I will have a look this weekend how to implement using the content class.

**Comment by Qoraiche** [comment]
> Hey @Qoraiche,
> 
> Sorry I've been slow on updating some things though.
> 
> But I was looking into making some adjustments that would allow it to work on both v8 and v9 of Mailable classes as I think you can still use the old way?
> 
> ```
>     public static function buildMailable($instance, $type = 'call')
>     {
> 🔶 // create a check here or later on in this method to change the method being called, either build / render...
>         if ($type === 'call') {
>             if (self::handleMailableViewDataArgs($instance) !== null) {
>                 return app()->call([self::handleMailableViewDataArgs($instance), 'build']);
>             }
> 
>             return app()->call([new $instance, 'build']);
>         }
> 
>         return app()->make($instance);
>     }
> ```
> 
> Specifically this part of the MailEclipse class, we could make it call the render method or the build method. Depending on what it is or the Laravel version.
> 
> But the PR linked gives more info on what I saw and does appear to allow for a cleaner approach that could be implemented. I will have a look this weekend how to implement using the content class.

yes you right we should keep it backward compatible maybe by checking if the built() method is present and callable or not otherwise we use the new content class approach if you have any other idea for a conditional use, you can implement it and we will pair it on the PR code 💡

**Comment by Qoraiche** [comment]
by the way I'm not quite sure if the built method is completely removed since laravel v9.37

**Comment by ReeceM** [comment]
> by the way, I'm not quite sure if the built method is completely removed since laravel v9.37

That part I'm not sure of myself, when I look at the mailable class that is extended by old and newer mailables. I think it didn't have a parent method before. But all new ones are created without it.

**Comment by Qoraiche** [comment]
> > by the way, I'm not quite sure if the built method is completely removed since laravel v9.37
> 
> That part I'm not sure of myself, when I look at the mailable class that is extended by old and newer mailables. I think it didn't have a parent method before. But all new ones are created without it.

If i recall i think that the build() method is not inherited or extended from another class but its directly called to build the view data using the container.

`````PHP
Container::getInstance()->call([$this, 'build']);
`````

Laravel 8:
https://github.com/laravel/framework/blob/36c2292735de11ea927b007cccb5be93ab2ad020/src/Illuminate/Mail/Mailable.php#L254

But here in laravel 9.x it still supported if its present in the mailable class:
https://github.com/laravel/framework/blob/912a40979dba77f51348a3358e6f1751cd521df7/src/Illuminate/Mail/Mailable.php#L1551

I think we need to do the same thing by simply checking if it exists or not, what you think @ReeceM?

**Comment by ReeceM** [comment]
That was the code I saw the other day when I was looking how they handled the older ones :) Forgot where it was 🤣

So I pushed to the fix branch related to this issue an idea to get this implemented. https://github.com/Qoraiche/laravel-mail-editor/tree/218-method-build-does-not-exist

There is a fix for performance that I saw can be done in the same area, will split that to a separate PR

**Comment by g0rath0r** [comment]
#218 also produces error:
[2022-11-14 02:26:23] local.ERROR: Attempt to read property "viewData" on string {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"viewData\" on string at J:\\xampp8.1\\htdocs\\tools.plantica.pl\\vendor\\qoraiche\\laravel-mail-editor\\src\\MailEclipse.php:716)

Maybe it's not elegant but these where work for me:

    public static function buildMailable($instance, $type = 'call')
    {
        if ($type === 'call') {
            if (self::handleMailableViewDataArgs($instance) !== null) {
                return app()->call([self::handleMailableViewDataArgs($instance), 'build']);
            }

            $mail = new $instance;
            $mail->view(app()->call([new $instance, 'content'])->view);
            return $mail;
//            $inst->view = app()->call([new $instance, 'build']);

            return app()->call([new $instance, 'build']);
        }

        return app()->make($instance);
    }

And for markdowns:

    protected static function getMarkdownViewName($mailable)
    {
        if ($mailable === null) {
            return;
        }

        $reflection = new ReflectionClass($mailable);

        $property = $reflection->getProperty('markdown');

        $property->setAccessible(true);

        $markdown = app()->call([new $mailable, 'content'])->markdown;

        return $markdown;

**Comment by ReeceM** [comment]
@g0rath0r thanks for the suggestion. I'm sure a fix doesn't have to be pretty 😁

When you say #218 isn't working is that the PR you are talking about?

**Comment by ReeceM** [comment]
Hi everyone,

Sorry it's taking a bit of time getting this patched. I'm making some progress in making this backward compatible as I suspect a majority of users have their old mail ales mixed with new ones.

**Comment by ReeceM** [comment]
Would it be possible for those who have been experiencing this bug please test out the dev branch with the fix

Its located here

```
composer require qoraiche/laravel-mail-editor:dev-218-method-build-does-not-exist
```

And if you could give feedback that would be great.

**Comment by ReeceM** [comment]
Hi everyone, please update to v4.0.4 as this should fix the issue. Many thanks for your patience
