### ISSUE TITLE
No template associated

### ISSUE THREAD

**Issue by dualznz** [Qoraiche/laravel-mail-editor#223]
## Describe the bug
When trying to open a a Mail template a error comes up with `no template found`, downgrade to version 4.0.3 and the template loads up fine.

markdown.template wont load in 4.0.4, also the footer of the application still shows 4.0.3 on 4.0.4

## Reproduction steps
1. Go to 'Mailables'
2. Click on 'a user made mailable'

## Laravel Version: 
9.44.0

## MailEclipse package version: 
4.0.4

## Screenshots (if applicable)
[https://i.imgur.com/vvKeixx.jpg](https://i.imgur.com/vvKeixx.jpg)

--- 

<details>
<summary> <b>Additional information</b></summary>
Mailables are in `qpp\mail\`
Templates are in `resources\views\markdown\`
</details>

**Comment by ReeceM** [comment]
Hi there @dualznz

If I understand correctly, the template was linked before and shows on the older version?

With the version name showing incorrectly at the base it is likely my fault not updating the version on the main class.

**Comment by dualznz** [comment]
that is correct, nothing changed in paths between 4.0.3 and 4.0.4

**Comment by ReeceM** [comment]
So I think I had this issue locally myself with templates and something with the names.

I will have a look again on my install, I recall something that the package was looking in a different directory although it's defined correctly. Didn't think more of the bug than being a local issue.
