### ISSUE TITLE
Undefined variable $exception when I added variable to Mail construct

### ISSUE THREAD

**Issue by xMrViktorx** [Qoraiche/laravel-mail-editor#224]
maileclipse/mailables/view/Testmail page.

Without variable, everything is okey, but If I add variable to __construct I get this error:
![image](https://user-images.githubusercontent.com/56076005/212468901-53a42bee-9a3c-4157-9210-45dc1c462dec.png)

I gone deeper and this is because when you add variable to construct, the view is null, and without view It can't render the preview.

$reflector->newInstanceArgs($resolvedTypeHints) doesn't give back view.

![image](https://user-images.githubusercontent.com/56076005/212468951-be053ff5-b66a-4444-9007-54b5c419d8c7.png)

**Reproduce the bug**

1. Create a mailable
2. Create a template
3. In the created mailable file add variable to construct
4. In the created mailable set the view insside the build function: return $this->view('mailTemplate');

Laravel Framework 8.42.1
MailEclipse v4.0.3

**Comment by elguitarraverde** [comment]
@xMrViktorx try remove $order from the constructor.

```php
/**
* Create a new message instance.
*
* @return void
*/
public $order;
public function __construct()
{
}
```

**Comment by ReeceM** [comment]
Hi @xMrViktorx 

I think the section of the code that is supposed to make use of the new laravel Mail class style and still use the old one is possibly causing this problem.

Sorry for the delay in response on this issue and a few others, I have to give priority to some other matters.

**Comment by meet-7span** [comment]
@ReeceM Any update on this? cause I'm also facing the same issue. I can't edit the template.

**Comment by ReeceM** [comment]
So it would be great if you can share a error message / trace. Also as mentioned earlier in the messages, I currently have a few things that need to be given priority. But I am happy to have a look, or if you would like to make a PR those are welcome.

**Comment by meet-7span** [comment]
@ReeceM 
![image](https://github.com/Qoraiche/laravel-mail-editor/assets/101455648/5838e826-3302-42a1-a610-c97621956db0)

When creating a new template, it is work fine. However, if you make the template content dynamic and need to pass data to the mailable class constructor, you may encounter an error on the Eclips list page.

**Comment by meet-7span** [comment]
@ReeceM 

we have tried with the below command but getting the same issue

to install on laravel 10,

composer require qoraiche/laravel-mail-editor:dev-master
or

composer require qoraiche/laravel-mail-editor:4.1.0-beta.0
