### ISSUE TITLE
Edit Templates of Editor

### ISSUE THREAD

**Issue by mtmSchoenberger** [Qoraiche/laravel-mail-editor#225]
How I can Edit the Template of the frontend:

![image](https://user-images.githubusercontent.com/55283261/214314022-db8238e5-0f7e-497e-a21b-a5e2bba1075b.png)
I would like to customise the menu and change the link from the footer as it goes nowhere.

I would also like to include all externally linked libraries like fontawesome locally.

**Comment by xMrViktorx** [comment]
The best option if you overwrite the whole package, and after that you can edit the footer.blade.php and the sidebar.blade.php files inside resources/views/layouts folder.

**Comment by ReeceM** [comment]
@mtmSchoenberger in all friendliness you are welcome to add those changes as it would be a great addition to change the font and icon sources. 

But at the moment I am not sure how that part of the package is working other than being defined in the main code. 

But you could try make use of the Laravel defaults that it can load and overwrite the views found under resources/views/vendor. Just matching the pattern that is in the package. 

I'll have a look tonight and maybe test that too

**Comment by mtmSchoenberger** [comment]
ok I have found a solution: https://laravel.com/docs/8.x/packages#overriding-package-views (I use Laravel 8 and maileclipse 3.5.3)
My setup is a little special so it didn't work right away.

But you can provide the templates as described here: https://laravel.com/docs/8.x/packages#publishing-views
So you don't have to search for a long time where the templates are.

**Comment by mtmSchoenberger** [comment]
Why is there a mix of icons here? 
Sometimes an svg is directly integrated, sometimes the font icon is used.
That should be standardised.
