### ISSUE TITLE
Requests for each change to the template may cause performance problems and delays?

### ISSUE THREAD

**Issue by mtmSchoenberger** [Qoraiche/laravel-mail-editor#226]
## Describe the bug
Performance Issue
Is it possible to stop already started requests while typing (preview generation)?

## Reproduction steps
In full screen view (left template right preview) Writing. 
Requests go off with every change.

## Laravel Version: 
8

## MailEclipse package version: 
3.5.3

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/55283261/214317446-7a83984c-6ff4-43b5-83e7-e4ba52c704f5.png)

**Comment by xMrViktorx** [comment]
Because it's a "live preview", I think not possible without requests while typing. If you have performance issues, then don't use it, or use tinymce.

**Comment by ReeceM** [comment]
Hi @mtmSchoenberger 

I'm not aware of the fact it was sending that many request on the preview side of things. 

@xMrViktorx the package actually uses tinymce, I am not sure if the comments added are much value ?

**Comment by ReeceM** [comment]
But it should be possible to reduce the number of requests as that is way too many because that's going to mess with things. 

I'm not sure what event is firing it but wrapping the request in a denounce function should work.

**Comment by xMrViktorx** [comment]
@ReeceM tinyMCE don't have live preview. He is editing markdown, where SimpleMDE is the default editor, and he is using live preview. And of course if live preview there are requests after every type.

**Comment by mtmSchoenberger** [comment]
The problem is that when you type something and then have to wait (depending on server performance) until all the previews have been generated and show. 

Would it be possible to send the request only after 1 second of not typing?

**Comment by ReeceM** [comment]
> The problem is that when you type something and then have to wait (depending on server performance) until all the previews have been generated and show. 
> 
> 
> 
> Would it be possible to send the request only after 1 second of not typing?

The delay after typing is what im suggestion should be implemented. Or maybe less. But we can make use of lodash for that.
