### ISSUE TITLE
Major Security Vulnerability 

### ISSUE THREAD

**Issue by akhan619** [Qoraiche/laravel-mail-editor#227]
Hello,

I reported a major security vulnerability at the email address provided on the Readme Page. However, no response on that. 

Is there any other channel to report it? I definitely don't want to discuss here about it.

**Comment by ReeceM** [comment]
Hello. 

Not sure why there isn't a response, but you can contact myself on my websites contact form https://reecemay.com/contact

**Comment by ReeceM** [comment]
@akhan619 please let me know if you got the above message

**Comment by Qoraiche** [comment]
> @akhan619 please let me know if you got the above message

@ReeceM, I've replied to the email, thank you!
