### ISSUE TITLE
Novapackage

### ISSUE THREAD

**Issue by cord** [Qoraiche/laravel-mail-editor#23]
good stuff!

A laravel nova package would be great!

**Comment by greggh** [comment]
This is exactly what I am looking for. Something that does all of this and integrates with Nova!

**Comment by Qoraiche** [comment]
@cord thank you for your suggestion, I will try my best to make this happen.

**Comment by JasonTheAdams** [comment]
Yeah, we use Nova and I'm not eager to have _another_ admin dash to send folks to. Having this integrated into Nova would be awesome. We'd pay for a package like that!

**Comment by nezaboravi** [comment]
Amazing package, and support a feature request for Nova package!

**Comment by fbingha** [comment]
Nova here too.

**Comment by vesper8** [comment]
+1 Use Nova extensively, would love a bridge between this package and Nova please
