### ISSUE TITLE
Laravel 10 support?

### ISSUE THREAD

**Issue by chiragsenjaliya** [Qoraiche/laravel-mail-editor#230]
Hey,

I am using this amazing package and needed to use it in laravel v10.

Hope It will update soon.

**Comment by ReeceM** [comment]
Hi there,

I don't think there were major changes on L10 that would break updating the composer deps to require laravel 10. So we could do that.

Would you be willing to pull a pre release to see if it works for you?

**Comment by ReeceM** [comment]
> Hi @ReeceM, I can be the tester of the pre-release :)

@YvanMARTY Thank you that would be awesome 💯

**Comment by chiragsenjaliya** [comment]
@ReeceM sure

**Comment by meet-7span** [comment]
@Qoraiche @ReeceM 
Do we have any information regarding when we can expect an official update for L10?

**Comment by ReeceM** [comment]
> @Qoraiche @ReeceM 
> 
> Do we have any information regarding when we can expect an official update for L10?
> 

Hi there @meet-7span so I am waiting for feedback from the pre release, you can give that a go.

**Comment by Shaz3e** [comment]
Any update on Laravel 10

**Comment by AimalAzmi** [comment]
Any updates on this?

**Comment by azaricstefan** [comment]
I tested locally on Laravel 10 and PHP 8.2, it works as expected.

**Comment by sandip-b-7span** [comment]
@azaricstefan i tried to install it in laravel10 and php8.2 but still not able to install this package.

**Comment by azaricstefan** [comment]
What command did you try?

**Comment by sandip-b-7span** [comment]
@azaricstefan  i tried the below command : 
composer require qoraiche/laravel-mail-editor

**Comment by azaricstefan** [comment]
You have to configure minimum stability to beta.

**Comment by sandip-b-7span** [comment]
@azaricstefan  yes, it is working now. 
Thank you

**Comment by azaricstefan** [comment]
@ReeceM can you move release to stable tag please?

Package is working as expected :)

**Comment by Stephan-MC** [comment]
to install on laravel 10, 

```bash
composer require qoraiche/laravel-mail-editor:dev-master
```
or
```bash
composer require qoraiche/laravel-mail-editor:4.1.0-beta.0
```
