### ISSUE TITLE
May I know the approx. release date of new version which is supported with Laravel 10?

### ISSUE THREAD

**Issue by riteshhirapara** [Qoraiche/laravel-mail-editor#238]
Right now I'm in the middle of development with Laravel 10 and I want to use this feature if any pre-tester version then I'm happy to use and testing.

**Comment by Stephan-MC** [comment]
to install on laravel 10, 

```bash
composer require qoraiche/laravel-mail-editor:dev-master
```
or
```bash
composer require qoraiche/laravel-mail-editor:4.1.0-beta.0
```

**Comment by riteshhirapara** [comment]
@Stephan-MC Thanks for the help but I already did it. Can you help me how to use created template to send my custom mail using the dashboard?
