### ISSUE TITLE
Can't locate path for templates

### ISSUE THREAD

**Issue by jcsoriano** [Qoraiche/laravel-mail-editor#24]
Hi!

First of all, thanks for the wonderful package! So I'm following the installation instructions, and hit an error on the second step, right after I run this:

```
php artisan vendor:publish --provider="qoraiche\mailEclipse\mailEclipseServiceProvider"
```

I get the following error:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/5937317/56031724-d09a8600-5d52-11e9-8ed7-4ae98fd19cba.png">

I checked the source code here in Github and it does indeed seems there's no templates folder in that path.

**Comment by Qoraiche** [comment]
Hello @jcsoriano,
 
Please update to the latest version and try again.
