### ISSUE TITLE
Cannot use object of type ReeceM\\Mocker\\Mocked as array 

### ISSUE THREAD

**Issue by ChiselspeedTuning** [Qoraiche/laravel-mail-editor#31]
I have created a mailable and then all of sudden on the /mailables route I get this error

`Cannot use object of type ReeceM\\Mocker\\Mocked as array `

**Comment by ChiselspeedTuning** [comment]
My bad, it was nothing related to this package

**Comment by ReeceM** [comment]
@ChiselspeedTuning, I see you had an issue related to the Mocker package, also you opened and closed the issue quickly 😄, if you are still having issues you can open an issue on [ReeceM/Mocker](https://github.com/ReeceM/mocker/issues/new/choose) :+1:
