### ISSUE TITLE
"Error: Request failed with status code 500" when updating template details

### ISSUE THREAD

**Issue by Qoraiche** [Qoraiche/laravel-mail-editor#32]
PR ref: https://github.com/Qoraiche/laravel-mail-editor/pull/13

To reproduce:
- create template
- edit template details (title, description)
- submit changes

UI error:
`Error: Request failed with status code 500`

XHR response message:
`message | Method Illuminate\Support\Collection::add does not exist.`

file | qoraiche/mailEclipse/src/mailEclipse.php
-- | --
line | 125
class | Illuminate\Support\Collection

**Comment by griffins** [comment]
Hi, just received this notification, on it.

**Comment by griffins** [comment]
check #33

**Comment by Daniel-HBK** [comment]
I had the same problem. CHMOD for app/Mail and app/resources/views/vendors/maileclipse/templates fixed that
