### ISSUE TITLE
mail_dir config for multiples folders

### ISSUE THREAD

**Issue by Atiladanvi** [Qoraiche/laravel-mail-editor#34]
I have a app laravel modulated. Each module contains your classes /Mails /Notifications etc. But i can't keep my workflow with mail eclipse because he know only one folder app_path('Mail/'). Is possible implements this for many folders ?

**Comment by Qoraiche** [comment]
Hello @Atiladanvi,

 I understand your problem but currently, you can only use one Mailable directory, try to copy all your mailables to one folder (eg `App/Mail`).

**Comment by Atiladanvi** [comment]
Canot be a array|string type to work in mailablesList() method ?

**Comment by Qoraiche** [comment]
I don't understand, do you get an error? can you elaborate, please?

**Comment by Atiladanvi** [comment]
I'm not getting an error.  I'm just wondering if it is possible to modify this behavior without breaking much of the core.  I think it could be modified at one point.  In the mailablesList method of the main class

**Comment by Qoraiche** [comment]
@Atiladanvi If you have an idea to support multiple Mailables directory you can pull request and I will check it out. thanks!
