### ISSUE TITLE
Views are deleted when you cleanup the aplication

### ISSUE THREAD

**Issue by a21ns1g4ts** [Qoraiche/laravel-mail-editor#36]
How add views to versioning ?

**Comment by Qoraiche** [comment]
Hello @Atiladanvi,

Template meta tags are saved to your `App\Mail` directory (**templates.json**) which is not ignored by git by default, if you are using the latest version of maileclipse, templates folder will be generated automatically for you when you create you first template: `resources/views/vendor/maileclipse/templates`, If the opposite, you can publish it with all email templates you 've created with the following command: `php artisan vendor:publish --tag=maileclipse.templates`

Hope this helps,
Checkout [Docs](https://maileclipse.io/public/docs/) for more informations.

**Comment by Atiladanvi** [comment]
@Qoraiche Do you think it's possible to change the code to save the templates in a place based on the namespace of the Email class without breaking the public api?

**Comment by Qoraiche** [comment]
@Atiladanvi nice idea, I will think about it.
thanks!
