### ISSUE TITLE
crud templates and mailables return status 419 response 

### ISSUE THREAD

**Issue by ffaouzif** [Qoraiche/laravel-mail-editor#39]
I have installed the package it work fine. Except on crud with axios return status response 419.
I have check csrf in axios setting and i found it all is normaly.
i don't know why he didn't arrived to the functions (crud).
any help please.
thank you.

**Comment by Qoraiche** [comment]
Do you have the **web** middlware in the maileclipse config file?

**Comment by ffaouzif** [comment]
Yes and i have add auth middlware to 
====>
'middlewares' => [
        'web',
        'auth',
    ],

**Comment by ffaouzif** [comment]
salam khouya yassine
rah jawbtek khouya mafhamtch 3lach ki reja3 status 419
rani chekit csrf
meli khademt ajax f blast axios khedmat mais ma b9atch katraraje3 message
de notification.
merciii khouya

Le mer. 12 juin 2019 à 19:22, Yassine Qoraiche <notifications@github.com> a
écrit :

**Comment by Qoraiche** [comment]
salam! Are you using the latest version?

**Comment by ffaouzif** [comment]
yes v1.2.3

**Comment by Qoraiche** [comment]
Thanks for reporting this, I will double-check this and get back to get very soon!

**Comment by ffaouzif** [comment]
Ok bro thank you

Le jeu. 13 juin 2019 à 00:44, Yassine Qoraiche <notifications@github.com> a
écrit :

**Comment by Qoraiche** [comment]
Unfortunately, I can't reproduce this issue, what laravel version are you using?

**Comment by ffaouzif** [comment]
Laravel 5.6

Le jeu. 13 juin 2019 à 20:04, Yassine Qoraiche <notifications@github.com> a
écrit :

**Comment by Qoraiche** [comment]
no one confirms this issue and can't reproduce it as well.
