### ISSUE TITLE
Class 'string' not found

### ISSUE THREAD

**Issue by matthewsuan** [Qoraiche/laravel-mail-editor#4]
Thanks for a really neat package.

I am running 5.8 and it seems its not compatible with this version yet?

```
"Class 'string' not found"
qoraiche/laravel-mail-editor/src/mailEclipse.php644
```

it seems this would not work if we have non object parameters in an existing mailable constructor?

**Comment by Qoraiche** [comment]
Thank you,

This issue is already mentioned in the [1st issue](https://github.com/Qoraiche/laravel-mail-editor/issues/1).

**Comment by matthewsuan** [comment]
@Qoraiche v1.1.0-alpha fixed it. ty
