### ISSUE TITLE
[Feature Request] add a 'send test email' to the UI

### ISSUE THREAD

**Issue by vesper8** [Qoraiche/laravel-mail-editor#41]
It would be very useful if you could add a button for each mailable, in the mailables view, where you can specify an email (or possibly a user id) and have a test sent to that email.

The preview is nice, but you really don't know for sure how an email is going to look until you send an actual test and preview it in Mailtrap or in your email client itself (Gmail for example)

This would be a nice convenience method that I would personally use

**Comment by Qoraiche** [comment]
Nice idea @vesper8, Actually I was working on this feature in my local! i just don't have time to finish it

### Feature:
- Can send a mailable to an email-address
- The given mailable will be sent to the given recipient. Any parameters handed to the __construct method of the mailable class will be automatically passed in.

Stay tuned for updates!
Thanks.

**Comment by vesper8** [comment]
that's great to hear!

I always pass a single object to my mailables and that payload is often represented as a json object

It would be cool if in your above test you could paste a json object to be passed to the test mail

this would also be very useful when previewing mailables

for example, and I suspect this is a pattern that many people use. For many of my mailables I reuse the same template / skeleton and based on a parameter in the payload, I dynamically change the message body

I could achieve this with your package but I'd have to duplicate many mailables, yes they'd all use the same template but the duplication of mailables is perhaps not necessary.

Hope this new test mail feature is added soon! Really enjoying playing around with your package so far!

**Comment by ReeceM** [comment]
For reference, this was added in v3.2.1, https://github.com/Qoraiche/laravel-mail-editor/releases/tag/v3.2.1 

Please let me know if this also can be closed, as there was another issue with a similar request. We could maybe keep this open

PR: https://github.com/Qoraiche/laravel-mail-editor/pull/122
