### ISSUE TITLE
Unable to deploy, get forbidden on every route

### ISSUE THREAD

**Issue by tanthammar** [Qoraiche/laravel-mail-editor#44]
I have deployed a development version on Heroku to share with my Team.
I am unable to access any of the Maileclipse routes. Get, 403 Forbidden.

I have uncommented  environment settings
```
//'allowed_environments' => ['local', 'staging', 'testing', 'development'],
``` 
And I have Route Middleware set to
```
'middlewares' => [
        'web',
        'auth',
    ],
```
Otherwise this is a clean installation of Laravel 5.8 with standarad "make: Auth"
No other packages are installed.
It is working fine on localhost.
I can login/logout on the deployed version and I can access the default "home" route that I also added to the auth middleware.
Any ideas?

**Comment by tanthammar** [comment]
resolved. 
The setting required 'allowed_environments' to be uncommented and the value 'deployment' was not accepted.
Changing the .env on the live server to 'staging' got me passed this error.

**Comment by parthkharecha** [comment]
![image](https://user-images.githubusercontent.com/67583304/102582031-c0da6400-4127-11eb-9d2b-f5ea96540ccd.png)
 
**_maileclipse.php_** 

Add `production` in allowed_environments array
