### ISSUE TITLE
Subject edit

### ISSUE THREAD

**Issue by paqio** [Qoraiche/laravel-mail-editor#46]
Is there a way to edit the subject?

**Comment by Qoraiche** [comment]
Currently you can not edit the mailable subject using the maileclipse package, but you still can set the mailable subject in your mailable class (build method), example:

```
public function build()
{
    return $this->subject('Your email subject here')
                ->view('emails.orders.shipped');
}
```

For more informations checkout laravel [writing mailables](https://laravel.com/docs/5.8/mail#writing-mailables).
