### ISSUE TITLE
[Feature Request] Mailables Change Markdown through frontend

### ISSUE THREAD

**Issue by chirumist** [Qoraiche/laravel-mail-editor#47]
Setup new mailable template or markdown after change then template on edit mailable

**Comment by Qoraiche** [comment]
Hi @chirumist, I don't understand, can you please elaborate?

**Comment by chirumist** [comment]
I am create mailable and set Markdown.
after edit mailable markdown not change.

![image](https://user-images.githubusercontent.com/35195295/63370778-841a2380-c3a0-11e9-8653-50ad877f26d4.png)

**Comment by Qoraiche** [comment]
@chirumist sorry for late, i will record this feedback, I'm gathering all information about what users need and I will implement it in the next coming updates.
