### ISSUE TITLE
REQUEST - Laravel 6 support

### ISSUE THREAD

**Issue by lstables** [Qoraiche/laravel-mail-editor#48]
Will or does this package allow for Laravel 6 which I believe is released tomorrow (3rd Sept)

**Comment by Qoraiche** [comment]
@lstables can you please confirm that it's working on the laravel 6?

**Comment by lstables** [comment]
At my last check 4 days ago, it didn't.

**Comment by codepotato** [comment]
I've created a PR to bring the dependencies up to L6 #49

**Comment by codepotato** [comment]
Just to update here, just updated my PR #50 to work with L6. Fully tested locally and working as expected.

**Comment by codepotato** [comment]
@Qoraiche can this issue be closed now with the latest release?

**Comment by Qoraiche** [comment]
@codepotato you right!
