### ISSUE TITLE
Type hints in mailable constructor must be an object

### ISSUE THREAD

**Issue by MartijnDB** [Qoraiche/laravel-mail-editor#52]
In my mailable contructor I have a typehint for int and it fails on that:
"Argument 1 passed to App\Mail\XXX::__construct() must be of the type int, object given"

**Comment by Qoraiche** [comment]
Hello @MartijnDB,

can please share your mailable?

**Comment by MartijnDB** [comment]
Sure. See the screenshot.
![Screenshot_2019-09-23, 11_39_09](https://user-images.githubusercontent.com/47593731/65415806-c6e37700-ddf6-11e9-8fd5-fd8d9e30e2a8.png)

**Comment by ReeceM** [comment]
@Qoraiche, and @MartijnDB.

I have had a look at it and initially there isn't a way to account for all the PHP builtin types as the __toString magic method allows for one to react to the `string` type hint. 

Things like the `int, bool, float` types need to be accounted for differently. 

I have a working patch on my local fork of the repo, I will clean it up and push it and you can test it as a PR on the main repo here.

Please let me know if this is okay?

**Comment by Qoraiche** [comment]
@ReeceM of course, thank you

**Comment by ReeceM** [comment]
HI @MartijnDB, release v1.3.2 should have fixed your issue you were experiencing with the mailables. Please do a composer update and reply back if it has fixed it +1

**Comment by MartijnDB** [comment]
Yes. Works as expected. Thanks.
