### ISSUE TITLE
https://maileclipse.io/ leads to Whoops Error page 

### ISSUE THREAD

**Issue by Yashaswini** [Qoraiche/laravel-mail-editor#54]
Hi,
I am unable to view your documentation. Is there a different link which I should be looking at?

**Comment by Qoraiche** [comment]
@Yashaswini thanks for reporting this!

**Comment by Yashaswini** [comment]
I wanted to try this package. Is there any other link where I can find the details.

**Comment by indowebdeveloper** [comment]
Facing this issue as well, is there any alternative documentation that maileclipse provide ? :D

**Comment by Qoraiche** [comment]
Follow the installation instructions here:
https://github.com/Qoraiche/laravel-mail-editor#installation

Maileclipse default path: `yoursite.com/maileclipse`
configuration: `config/maileclipse.php`

Hope this helps.

**Comment by Yashaswini** [comment]
Thank you so much for your response

**Comment by Qoraiche** [comment]
@Yashaswini @indowebdeveloper if you guys like my project don't forget to give it a star 👍

**Comment by Qoraiche** [comment]
https://maileclipse.io/ up again!
