### ISSUE TITLE
Cannot see templates

### ISSUE THREAD

**Issue by adriancampanaro** [Qoraiche/laravel-mail-editor#57]
Hi
I am installed this package and cannot see the templates in 
[\vendor\qoraiche\laravel-mail-editor\resources\views\templates

It shows file just file .gitkeep

![mail_editor](https://user-images.githubusercontent.com/7865012/66749874-b2b30700-eed6-11e9-990e-5f0f9e304135.jpg)

**Comment by Qoraiche** [comment]
All email templates are stored in the following directory: resources/views/vendor/maileclipse/templates, it will be generated for you when you create your first template.

if you still can't see it you can publish the templates folder using the following command:

`php artisan vendor:publish --tag=maileclipse.templates`

**Comment by adriancampanaro** [comment]
I am new to this.
How to I create my first template.
How do I run this application?

**Comment by Qoraiche** [comment]
Hi @adriancampanaro,

checkout the documentation here (there is a video tutorial there): 
https://maileclipse.io/public/docs/

**Comment by adriancampanaro** [comment]
thanks...worked now
