### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by kennyhorna** [Qoraiche/laravel-mail-editor#59]
This doens't have to do with the package itself but the website of the package (https://maileclipse.io/) that is throwning a `500 ` error page.

![image](https://user-images.githubusercontent.com/16125117/67165485-275cca00-f34b-11e9-8922-153612c1f2dc.png)

Just that. I hope you (@Qoraiche ) can manage to fix it :)

**Comment by Qoraiche** [comment]
Maileclipse Docs up, home and demo pages are under construction

**Comment by kennyhorna** [comment]
Oh, I see.
