### ISSUE TITLE
Uncaught SyntaxError: Invalid hexadecimal escape sequence

### ISSUE THREAD

**Issue by MujahidAbbas** [Qoraiche/laravel-mail-editor#6]
Hi there, thank u for this awesome package!

Creating template first time is hassle-free. After attaching mailable to the template, when I view the mailable, the editor is not working. In the console, I am getting this error:
`Uncaught SyntaxError: Invalid hexadecimal escape sequence`

Can you please help me?

![Uncaught SyntaxError- Invalid hexadecimal escape sequence](https://user-images.githubusercontent.com/21082153/54903106-edcef800-4efc-11e9-8340-1df15e5a9499.PNG)

**Comment by Qoraiche** [comment]
Hi @MujahidAbbas, Thanks for reporting this,

Please update to the latest version (currently v1.1.1) and tell me if it's working.

**Comment by MujahidAbbas** [comment]
Yes, thank u soo much... the issue is fixed now!!
