### ISSUE TITLE
Giving variable in  Url in button component 

### ISSUE THREAD

**Issue by omkar3524** [Qoraiche/laravel-mail-editor#60]
I want to make a button for activate account. but giving a variable give me error.
My variable is  $link  which look like (http://localhost/activate/ $token)
![link](https://user-images.githubusercontent.com/22766237/68072524-ca323100-fdac-11e9-91ac-19b2c08dfc6b.png)

How to pass variable ?

**Comment by Qoraiche** [comment]
Just pass the variable without the curly braces `'url' => $link`

Hope this helps.

**Comment by Qoraiche** [comment]
hope my answer fixes your issue

**Comment by omkar3524** [comment]
Thanks , it works
