### ISSUE TITLE
Unable to Open the Route(http://127.0.0.1:8000/maileclipse/mailables Route not Found)

### ISSUE THREAD

**Issue by vin33t** [Qoraiche/laravel-mail-editor#62]
Installed the package successfully but when I tried to open 

> /maileclipse/mailables

I got 404 page not found

![image](https://user-images.githubusercontent.com/13203976/68996136-05a82180-08bc-11ea-9ae0-8e62d84c2a3f.png)

**Comment by Qoraiche** [comment]
Hi, did you publish the package config and service provider files?

**Comment by vin33t** [comment]
Yes, I did
![image](https://user-images.githubusercontent.com/13203976/69003639-cf09ef80-092b-11ea-91ae-3eb0c8fda4c5.png)

**Comment by eapostol** [comment]
I am getting the same issue, after installing it in another laravel project successfully.

I am trying to determine the difference between the two. @Qoraiche  I am getting the same issue as @vin33t .

My setup involves using the laravel homestead vagrant vm. I have two laravel projects in the vm, in different directories (ex. /laravel-a and laravel-b.

I followed the installation instructions for MailEclipse in the /laravel-a folder without any issues. I browsed to https://originaldomain.com/maileclipse/mailables without any issues.

I then followed the same installation instructions for MailEclipse in the /laravel-b folder. No errors popped up during the installation. but browsing to https://somedomain.com/maileclipse/mailables is returning the **404 | Not Found** error. 

However -

@vin33t  I was able to browse to it after inspecting the list of routes using

`php artisan route:list`

and noting that the link for mailables actually ended up being https://somedomain.com/mailables. Not sure how it ended up that way though, but it works. Hope it does the same for you.

![mailables-url-for-test-email](https://user-images.githubusercontent.com/565104/69019794-28037300-0980-11ea-8cfa-fd737aa8ff6e.png)

**Comment by Qoraiche** [comment]
that's weird, could you please share more information like which laravel version you're using, also i can't see that the mailables URI ends with a dot in the screenshot you've shared?

**Comment by vin33t** [comment]
"php": "^7.1.3",  
"laravel/framework": "5.8.35"

![image](https://user-images.githubusercontent.com/13203976/69025013-38046c80-09eb-11ea-90b5-d15758eb6fe1.png)

@Qoraiche I don't understand why is it not working. I have tried removing and reinstalling it but still not working

**Comment by Qoraiche** [comment]
there may be a problem with autoloading, try to register it manually in your config/app.php

`qoraiche\mailEclipse\mailEclipseServiceProvider`

**Comment by hemratna** [comment]
I am also facing the similar issue.

In fact after installing the package, 
when I run the `php artisan route:list` it gives below error.

```
 Symfony\Component\HttpKernel\Exception\HttpException  :

  at /Applications/MAMP/htdocs/pagemaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1014
    1010|         if ($code == 404) {
    1011|             throw new NotFoundHttpException($message);
    1012|         }
    1013|
  > 1014|         throw new HttpException($code, $message, null, $headers);
    1015|     }
    1016|
    1017|     /**
    1018|      * Register a terminating callback with the application.

  Exception trace:

  1   Illuminate\Foundation\Application::abort("", [])
      /Applications/MAMP/htdocs/pagemaker/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:46

  2   abort("", [])
      /Applications/MAMP/htdocs/pagemaker/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:87

  Please use the argument -v to see more details.
```

My setup:
MAMP PRO
PHP: PHP 7.3.3
Laravel: ^6.0

P.S. By remove this package, `php artisan route:list` works as expected.

**Comment by hemratna** [comment]
@vin33t @eapostol Did you guys got and solution/workaround? 
Any help regarding this is really helpful. 🙏

**Comment by hemratna** [comment]
I resolved my issue.
In my case, I have `APP_ENV=development` in `.env` file.
So I added the `development` `allowed_environments` in the `config\maileclipse.php` and it works.
I hope it works for you too.

**Comment by vin33t** [comment]
@hemratna @Qoraiche I am still not able to figure out why its not working.

**Comment by satyam147** [comment]
Please try /mailables.

**Comment by satyam147** [comment]
> @Qoraiche I found out why it was not working. Turns out it the error has nothing to do with the route discovery or autoloading.
> 
> Please Have a look at one of my mailable below
> I am passing data to my mailable like
> `Mail::to($this->details['email'])->send(new SendEkit($this->details['id']));`
> 
> `<?php
> 
> namespace App\Mail;
> 
> use App\Client;
> use Illuminate\Bus\Queueable;
> use Illuminate\Mail\Mailable;
> use Illuminate\Queue\SerializesModels;
> use Illuminate\Contracts\Queue\ShouldQueue;
> 
> class SendEkit extends Mailable
> {
> use Queueable, SerializesModels;
> 
> ```
> /**
>  * Create a new message instance.
>  *
>  * @return void
>  */
> public $id;
> public function __construct($id)
> {
>     $this->id = $id;
> }
> 
> /**
>  * Build the message.
>  *
>  * @return $this
>  */
> public function build()
> {
>     $details = Client::findOrFail($this->id);
> 
>     return $this->from('noreply@example.com', 'Example Mail')
>         ->subject('Certificate |'. $details->name)->view('emails.certificate')->with('details',$details);
> }
> ```
> 
> }
> `
> ![image](https://user-images.githubusercontent.com/13203976/69912629-f2678b00-1451-11ea-9cb2-4a39e285d779.png)
> 
> If replace `$details = Client::findOrFail($this->id);` with `$details = Client::findOrFail(some specific id);` then its working fine.
> 
> Please Fix this. It'll be really helpfull 👍

Please try this $details = Client::findOrFail($id);
You doesn't have to use $this->id as you have declared it in the constructor.

**Comment by satyam147** [comment]
> Installed the package successfully but when I tried to open
> 
> > /maileclipse/mailables
> 
> I got 404 page not found
> 
> ![image](https://user-images.githubusercontent.com/13203976/68996136-05a82180-08bc-11ea-9ae0-8e62d84c2a3f.png)

Please try 
> /mailables.

**Comment by Qoraiche** [comment]
A new upgrade is coming btw, all route behavior would be changed in the next coming versions.

Thank you.

**Comment by Qoraiche** [comment]
hello, just an update on this, the way everyone fixes this issue as seen in the previous comments makes me believe that it has nothing to do directly with routes but more with configuration and construction building that @ReeceM keeps fixing, for the time being, I will close this until we got a reopen.

Thanks,
Qoraiche
