### ISSUE TITLE
Feature: multiply mailables_dir

### ISSUE THREAD

**Issue by 4n70w4** [Qoraiche/laravel-mail-editor#67]
Case: I separate my apps on modules, for example via https://github.com/nWidart/laravel-modules

Each module has a separate directory for emails like `base_path('Modules/*/Mail/')`.
and `app_path('Mail/')` of cource.

It will be very cool to be able to work with many directories at the same time.

**Comment by Qoraiche** [comment]
Thanks for reporting, will be added to next coming updated!
