### ISSUE TITLE
Mailable table width too small

### ISSUE THREAD

**Issue by 4n70w4** [Qoraiche/laravel-mail-editor#68]
![image](https://user-images.githubusercontent.com/38257723/75865482-ad6a4080-5e14-11ea-8a1d-05d2ff5a2f24.png)

Table is very small, scroll appears, very uncomfortable use for users.

**Comment by Qoraiche** [comment]
Thanks for your feedback, I believe it will be fixed in next coming updates!

**Comment by ReeceM** [comment]
I don't think I have seen this issue anymore, it can be reopened if there is an issue
