### ISSUE TITLE
Missing 1 type from the __constructor injection (array)

### ISSUE THREAD

**Issue by Cannonb4ll** [Qoraiche/laravel-mail-editor#7]
I've used this package a while ago, you've made some fixes but I am still running into one:

```
Argument 1 passed to App\Mail\ContactEmail::__construct() must be of the type array, string given
```

```php
    use Queueable, SerializesModels;
 
    public $data;
 
    /**
     * Create a new message instance.
     *
     * @param array $data
     */
    public function __construct(array $data = [])
    {
        $this->data = $data;
    }
 ```

**Comment by Qoraiche** [comment]
Hi @Cannonb4ll, thanks for reporting this,

The new version (currently v1.1.2) may fix the constructor problem, but still not able to show array data on mailable previews.

**Comment by Qoraiche** [comment]
@Cannonb4ll can you please confirm that is working? so I can close the ticket

**Comment by Cannonb4ll** [comment]
Ah yes sorry, it is solved this way 👍
