### ISSUE TITLE
Exception: Trying to access array offset on value of type null in resources/views/sections/edit-mailable-template.blade.php

### ISSUE THREAD

**Issue by 4n70w4** [Qoraiche/laravel-mail-editor#70]
![image](https://user-images.githubusercontent.com/38257723/75870825-a1827c80-5e1c-11ea-860c-d6389bbac2dc.png)

**Comment by mshoaibdev** [comment]
Having same issue. Any fix on this?

**Comment by lstables** [comment]
Wonder if and when this will be merged. I have just encountered the same problem.

**Comment by lstables** [comment]
`isset($param['data']['type']) && $param['data']['type'] ===` also needs adding for the `elequent-collection` and `collection` too, adding this myself solves the problem.

**Comment by oliverbj** [comment]
I have encounted exact same issue.

**Comment by lstables** [comment]
@Qoraiche is this now closed as the PR is merged?

**Comment by Qoraiche** [comment]
@lstables should be fixed by merging https://github.com/Qoraiche/laravel-mail-editor/pull/86, in https://github.com/Qoraiche/laravel-mail-editor/releases/tag/v1.4.3

**Comment by lstables** [comment]
Great, yes after a composer update that seems to have fixed it, Thank you and awesome package :)
