### ISSUE TITLE
Need show embed images

### ISSUE THREAD

**Issue by 4n70w4** [Qoraiche/laravel-mail-editor#71]
In email templates I use `{{$message->embed(public_path('i/slojj-2.png'))}}` instead direct links to images.

```html
<img src="cid:446cd432636b61d9409244e6f3acd9d7@swift.generated" alt="" border="0" width="120px">
```

![image](https://user-images.githubusercontent.com/38257723/72900388-d4732400-3d38-11ea-978e-d94569510008.png)

https://laravel.com/docs/6.x/mail#inline-attachments

**Comment by 4n70w4** [comment]
How is this done in another plugin: https://github.com/gabrieliuga/laravel-mail-log/blob/6a092a630c3c406e6d9f23bdd688d33d9975e0d7/src/Listeners/MailSentListener.php#L37

**Comment by Qoraiche** [comment]
thanks for the feedback, will look into it in next coming updates

**Comment by ReeceM** [comment]
> How is this done in another plugin: https://github.com/gabrieliuga/laravel-mail-log/blob/6a092a630c3c406e6d9f23bdd688d33d9975e0d7/src/Listeners/MailSentListener.php#L37

This is a good issue to begin with for someone who is comfortable with handling the internals of pre-displaying the rendered images.

The file linked makes use of bas64 encoding and embedding the data object in the email. **If you use the code from that file or use parts of it, please attribute it** If not it will be done so in the review process
