### ISSUE TITLE
Break mailable table if in any Mailable throws Exception in build()

### ISSUE THREAD

**Issue by 4n70w4** [Qoraiche/laravel-mail-editor#73]
```php
class Mail extends Mailable {

    public function build() : self {
        throw new \Exception('Oops');
    }
```

![image](https://user-images.githubusercontent.com/38257723/75880861-22e30a80-5e2f-11ea-96c3-ae63b13e242f.png)

But expected show table in any cases:
![image](https://user-images.githubusercontent.com/38257723/75880909-41e19c80-5e2f-11ea-9dec-bd2f96427dac.png)

**Comment by Qoraiche** [comment]
Thanks for reporting, will be fixed in next upcoming updates!

**Comment by ReeceM** [comment]
Just noting that this is still an issue. It should be possible to handle this by wrapping the loading part of the call in a `rescue` callback or a `try catch` and return a response code that can be handled on the front end or the view file.
