### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by vesper8** [Qoraiche/laravel-mail-editor#77]
`1.3.3` is not compatible with Laravel 7 due to `illuminate/support ~5|~6`

@Qoraiche Could you please release a new version with Laravel 7 compatibility?

Thanks a lot!

**Comment by Qoraiche** [comment]
Hi @vesper8,
thanks for letting me know.

Fix PR: https://github.com/Qoraiche/laravel-mail-editor/pull/66
