### ISSUE TITLE
Feature: show Subject in Mailables table instead Namespace and Name

### ISSUE THREAD

**Issue by 4n70w4** [Qoraiche/laravel-mail-editor#79]
Users do not understand what namespace is, they understand the headline of the letter.

**Comment by KieronWiltshire** [comment]
Also, not sure the current method would scale cross nodes.

**Comment by Qoraiche** [comment]
@4n70w4 would be great if you open a PR for this

**Comment by Qoraiche** [comment]
@KieronWiltshire this is planned for the next updates

**Comment by Qoraiche** [comment]
> Also, not sure the current method would scale cross nodes.

@KieronWiltshire this is planned for the next updates

**Comment by KieronWiltshire** [comment]
@Qoraiche to be honest, I can't see myself currently using this as I have already adopted my own solution using grapesjs and Twig, perhaps take a look at that? If you could create a package that utilizes grapesjs for design, and twig for processing email placeholders, I would probably consider using it in future projects!

**Comment by AEK-BKF** [comment]
Any updates here ?

**Comment by ReeceM** [comment]
Hi there @AEK-BKF, I will see if it is possible to push out the changes to make it possible to show this option this evening maybe. It wasn't an immediate thing at the moment since 2020 sometime

**Comment by ReeceM** [comment]
Will be made available in version 3 and version 4

**Comment by AEK-BKF** [comment]
@ReeceM Thank you dear :)
