### ISSUE TITLE
Everytime I visit the 'maileclipse/mailables' it creates a bunch of fake users

### ISSUE THREAD

**Issue by salhdev** [Qoraiche/laravel-mail-editor#8]
Hi,
Everytime I visit the 'maileclipse/mailables' path it creates a bunch of fake users.
Thanks for sharing this great package !

**Comment by Qoraiche** [comment]
Hi @salhdev,
Can you please explain with more details or with a screenshot!

**Comment by salhdev** [comment]
Hi, 
There is not much I can add to this. 
All I did is I created a Newsletter with a User  : 

```
namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;
use App\Models\User;

class NewsLetter extends Mailable
{
    use Queueable, SerializesModels;

    public $username = '';
    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct(User $user)
    {
        $this->username = $user->name;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->view('maileclipse::templates.testNewsletter');
    }
}

```
And now everytime I visit the path http://myhost.test/maileclipse/mailables I find that my user table has grown with random users. And I delete the users and refresh the page and get new ones every single time.
When I click on preview, it will generate another set of users :( 
I have updated to the latest version (1.1.0 => v1.1.2) but still the same happens.
I was just testing the package and stumbled into this, I can't be much more of a help here.
Thanks again,

**Comment by salhdev** [comment]
Hi again,
After taking a quick view at the code I noticed that the function handleMailableViewDataArgs in mailEclipse Class generates data without testing whether the table has data or not, so it will generate every time the function is called.

**Comment by Qoraiche** [comment]
Hi @salhdev, Thanks for report this! 
I made some changes lately but I didn't realize that this is happen in the database, please check out the new version (currently **v1.1.3**, commit https://github.com/Qoraiche/laravel-mail-editor/commit/97a764aea8535fd0ec294a240f0124882a9d8399) it will fix your problem.

Thanks again!

**Comment by Qoraiche** [comment]
@salhdev can you please confirm that the problem is fixed?
