### ISSUE TITLE
[Feature] - How to upgrade from previous version

### ISSUE THREAD

**Issue by eapostol** [Qoraiche/laravel-mail-editor#81]
Hello -

I was wondering if there are guidelines / steps to upgrading from an older version of laravel-mail-editor / MailEclipse? 

Thanks

**Comment by Qoraiche** [comment]
Hi @eapostol 

which version you're using? if you're using an old version( less than **v1.2**) you may need to publish the templates folder using the following command:

````
php artisan vendor:publish --tag=maileclipse.templates
````

**Comment by eapostol** [comment]
Hi @Qoraiche  - it's version 1.3 

![cl-maileclipse-version](https://user-images.githubusercontent.com/565104/77363617-71e2d800-6d29-11ea-8f1e-517542fd9985.png)

Just want to ensure that no data is lost (templates or otherwise). We're doing backups but just want to be sure.

**Comment by Qoraiche** [comment]
sorry for the late reply, going to add upgrading steps to docs soon
