### ISSUE TITLE
Request failed with status code 500 -Update Templates 

### ISSUE THREAD

**Issue by keatwei** [Qoraiche/laravel-mail-editor#9]
Not able to update Templates. shown error 500
Using homestead

[2019-03-28 15:50:19] local.ERROR: : failed to open stream: Protocol error {"exception":"[object] (ErrorException(code: 0): : failed to open stream: Protocol error at /home/vagrant/VM/Projects/Web/ding-web/vendor/qoraiche/laravel-mail-editor/src/mailEclipse.php:360)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, ': failed to ope...', '/home/vagrant/V...', 360, Array)
#1 /home/vagrant/VM/Projects/Web/ding-web/vendor/qoraiche/laravel-mail-editor/src/mailEclipse.php(360): file_put_contents('r\\x89\\xA9\\x95\\xEB^R\\xC7\\xAB>\\xBA\\x1F\\x8AW', '<!DOCTYPE html ...')
#2 /home/vagrant/VM/Projects/Web/ding-web/vendor/qoraiche/laravel-mail-editor/src/Http/Controllers/MailablesController.php(89): qoraiche\\mailEclipse\\mailEclipse::markdownedTemplateToView(true, '<!DOCTYPE html ...', 'r\\x89\\xA9\\x95\\xEB^R\\xC7\\xAB>\\xBA\\x1F\\x8AW', true)
#3 [internal function]: qoraiche\\mailEclipse\\Http\\Controllers\\MailablesController->parseTemplate(Object(Illuminate\\Http\\Request))
#4 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('parseTemplate', Array)
#6 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(qoraiche\\mailEclipse\\Http\\Controllers\\MailablesController), 'parseTemplate')
#7 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#8 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#9 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#12 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#13 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#14 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#15 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#16 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/vagrant/VM/Projects/Web/ding-web/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /home/vagrant/VM/Projects/Web/ding-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#35 /home/vagrant/VM/Projects/Web/ding-web/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#36 {main}
"}

**Comment by Qoraiche** [comment]
Hi @keatwei, Thanks for reporting this!

I've fixed this issue, can you please update to the latest release (currently **v1.1.4**) - Checkout fix commit https://github.com/Qoraiche/laravel-mail-editor/commit/2a2db2b058f99aba1cd0801f51fb63ae26dd896b.

**Comment by Daniel-HBK** [comment]
I had the same problem. CHMOD for app/Mail and app/resources/views/vendors/maileclipse/templates fixed that
