### ISSUE TITLE
Modularize

### ISSUE THREAD

**Issue by robov** [Qoraiche/laravel-mail-editor#92]
Is this compatible with nwidarts modules, so I can split up my mailables in modules

**Comment by robov** [comment]
It looks like the code can only handle 1 root directory for all mailables and rendered templates. Would be nice if it could handle more directories and subdirectories so we can modularize the mails

**Comment by Qoraiche** [comment]
coming soon @robov, we're working on this feature, thanks for your feedback!

**Comment by robov** [comment]
AWESOME !

**Comment by quentingosset** [comment]
> coming soon @robov, we're working on this feature, thanks for your feedback!

I'm using the laravel-module and I was going to ask the same question but since the topic is open I'll follow the evolution of this one. 
In any case thank you Qoraiche for your module.

**Comment by limsocheat** [comment]
Hi, any news about how to implement with nwidarts modules? 
Thanks.
