### ISSUE TITLE
Feature to send test emails

### ISSUE THREAD

**Issue by mayank2108** [Qoraiche/laravel-mail-editor#98]
Preview also must be made available for mobile and desktop to check responsiveness.

And then there should be a send button to test email.

**Comment by Qoraiche** [comment]
hello @mayank2108,

Thanks for your feedback, I believe this will be available in the next major updates

stay tuned!

**Comment by ReeceM** [comment]
Tagging for issue relation -> #41

**Comment by Qoraiche** [comment]
Preview for mobile and desktop feature will be resolved here: https://github.com/Qoraiche/laravel-mail-editor/issues/123

**Comment by Qoraiche** [comment]
Feature added in https://github.com/Qoraiche/laravel-mail-editor/releases/tag/v3.2.1.
